### ISSUE TITLE
T06.01-Exercise-SetupTheActivity - The lines are not moving

### ISSUE THREAD

**Issue by persev03** [udacity/ud851-Exercises#100]
i have a problem with the excercise "T06.01-Exercise-SetupTheActivity". I run the solution in my Galaxy Edge S7. But, not run as it should. I have tried in other device (Samsung Galaxy J7, Android 7.0), and it runs without any problem. 

Thanks.

![uploaded-file](https://cloud.githubusercontent.com/assets/25309049/23568084/137f4996-0027-11e7-8334-f18d323d6ff1.png)

**Comment by johnshea** [comment]
Closing this issue as it is not related to the repo's code.
