### ISSUE TITLE
Unable to create file "...": Filename too long

### ISSUE THREAD

**Issue by ericcleao** [udacity/ud851-Exercises#101]
Error while cloning github repository. Error happen after fork the repository and tried clone into my machine (my OS is Windows 10).

Error:
"Cloning into 'ud851-Exercises'...
remote: Counting objects: 4160, done.
remote: Total 4160 (delta 0), reused 0 (delta 0), pack-reused 4159
Receiving objects: 100% (4160/4160), 3.70 MiB | 366.00 KiB/s, done.
Resolving deltas: 100% (1807/1807), done.
Checking connectivity... done.
error: unable to create file Lesson06-Visualizer-Preferences/T06.01-Exercise-SetupTheActivity/app/src/main/java/android/example/com/visualizerpreferences/AudioVisuals/AudioInputReader.java: Filename too long
error: unable to create file Lesson06-Visualizer-Preferences/T06.01-Exercise-SetupTheActivity/app/src/main/java/android/example/com/visualizerpreferences/AudioVisuals/TrailedShape.java: Filename too long
error: unable to create file Lesson06-Visualizer-Preferences/T06.01-Exercise-SetupTheActivity/app/src/main/java/android/example/com/visualizerpreferences/AudioVisuals/VisualizerView.java: Filename too long
error: unable to create file Lesson06-Visualizer-Preferences/T06.01-Solution-SetupTheActivity/app/src/main/java/android/example/com/visualizerpreferences/AudioVisuals/AudioInputReader.java: Filename too long
error: unable to create file Lesson06-Visualizer-Preferences/T06.01-Solution-SetupTheActivity/app/src/main/java/android/example/com/visualizerpreferences/AudioVisuals/TrailedShape.java: Filename too long
error: unable to create file Lesson06-Visualizer-Preferences/T06.01-Solution-SetupTheActivity/app/src/main/java/android/example/com/visualizerpreferences/AudioVisuals/VisualizerView.java: Filename too long
fatal: cannot create directory at 'Lesson06-Visualizer-Preferences/T06.02-Exercise-MakeAPreferenceFragment/app/src/main/java/android/example/com/visualizerpreferences/AudioVisuals': Filename too long"

**Comment by jameslyleyoung** [comment]
I had a similar issue, because I have my files in my computer laid out extensively.  

I just had to move the entire download up a couple levels in my hierarchy tree.

**Comment by jwill** [comment]
We don't actively monitor this issue list enough to guarantee timely help. If you are enrolled in the Nanodegree program, I encourage you to consult a mentor. 

If you are enrolled in the free course, you can ask your question in the forums here: https://discussions.udacity.com/c/standalone-courses/developing-android-apps
