### ISSUE TITLE
T10.02 Typo in resource ID

### ISSUE THREAD

**Issue by gabor-meszaros** [udacity/ud851-Exercises#102]
In [this line](https://github.com/udacity/ud851-Exercises/blob/student/Lesson10-Hydration-Reminder/T10.02-Exercise-CreateNotification/app/src/main/java/com/example/android/background/utilities/NotificationUtils.java#L14) the resource ID should be `R.color.colorPrimary`.

**Comment by croworc** [comment]
Got hawk's eyes?! Impressive!
;-)

**Comment by johnshea** [comment]
Fixed.
