### ISSUE TITLE
T10.04 Typo in the comment

### ISSUE THREAD

**Issue by gabor-meszaros** [udacity/ud851-Exercises#104]
Hi, The first one is [in the exercises TODO](https://github.com/udacity/ud851-Exercises/blob/student/Lesson10-Hydration-Reminder/T10.04-Exercise-PeriodicSyncWithJobDispatcher/app/src/main/java/com/example/android/background/sync/WaterReminderFirebaseJobService.java#L28):

    // TODO (8) Override onPostExecute and called jobFinished.

And the same text [in the solutions](https://github.com/udacity/ud851-Exercises/blob/student/Lesson10-Hydration-Reminder/T10.04-Solution-PeriodicSyncWithJobDispatcher/app/src/main/java/com/example/android/background/sync/WaterReminderFirebaseJobService.java#L64):

    // COMPLETED (8) Override onPostExecute and called jobFinished.

If you prefer a PR for such a trivial issues, please let me know. Thank you!

**Comment by johnshea** [comment]
Fixed.
