### ISSUE TITLE
T02.06 - Typo in reference

### ISSUE THREAD

**Issue by Halfacht** [udacity/ud851-Exercises#105]
// TODO (12) Create a variable to store a reference to the error message TextView
    TextView **errorMessageTextView**;

// TODO (13) Get a reference to the error TextView using findViewById
        **errorMessageTextView** = (TextView) findViewById(R.id.tv_error_message_display);

Should have been mErrorMessageDisplay

**Comment by johnshea** [comment]
Resolved.
