### ISSUE TITLE
T05a.03-Solution: Bug with writing onStop in the TextView

### ISSUE THREAD

**Issue by cristianberroeta** [udacity/ud851-Exercises#108]
"onStop" is written twice instead of once in the TextView (as shown in the screenshot) if you follow these steps:

1. run the app
2. press the "Overview" or "Recents" device button
3. press the image to restart the Lifecycle app in the "Overview"
4. rotate the device (I started with horizontal orientation, just to be able to take a vertical orientation screenshot)

![image](https://cloud.githubusercontent.com/assets/17519897/23783741/8ff6da06-053c-11e7-9ffe-815f5d2308f6.png)

To solve this bug, you could add to `onRestart()` the following line:
`mLifecycleCallbacks.clear();`

The bug happens because, after pressing the "Overview" device button, the "onStop" String is added to `mLifecycleCallbacks` and also to the TextView (it's just that it's not visible). Then `onRestart` gets called, and now the activity's `mLifecycleCallbacks` incorrectly contains an "onStop" String, that will eventually be printed to the TextView again if `onCreate` gets called.

**Comment by johnshea** [comment]
Unable to duplicate.
