### ISSUE TITLE
T04b.02-Solution-OpenMap. Append query parameter

### ISSUE THREAD

**Issue by funnygerman** [udacity/ud851-Exercises#118]
In the T04b.02-Solution-OpenMap (#57) I think we should use appendQueryParameter instead of query

**Comment by CrisBarreiro** [comment]
I think so. Using query we get: 
`geo:/0,0?1600 Amphitheatre Parkaway, CA`
Using appendQueryParameter("q", address") we get
`geo:/0,0?q=1600 Amphitheatre Parkaway, CA`
which is the right one

**Comment by cbetta** [comment]
Agreed!

**Comment by kondratk** [comment]
Agree. The original way does not pass parameters to google maps correctly. AppendQueryParameter fixes the issue.

**Comment by Sgeo** [comment]
Interestingly, the quiz before this exercise got the concept of query wrong, saying that in a URL with `?q=Montreal,Canada`, the query was `Montreal,Canada`

**Comment by johnshea** [comment]
Fixed.
