### ISSUE TITLE
The following classes could not be found: android.support.contraing.FrameLayout

### ISSUE THREAD

**Issue by AlpineTech** [udacity/ud851-Exercises#13]
Followed instructions in lesson 1.  Replaced ConstraintLayout with FrameLayout and in the designer this error message appeared:   "The following classes could not be found: android.support.contraint.FrameLayout".  However, the project would still build and deploy, but crashed at runtime with a similar message.  

I was able to resolve the issue by deleting the activity_main.xml and re-adding a new activity through the IDE.   I noticed that when it added to the FrameLayout, it did not specify the fully qualified class name "android.support.contraint.FrameLayout".  Rather it simply specified "FrameLayout".  I opened the corresponding solution project and noticed it also did not have the fully qualified name.  This must be an issue that is only in the exercize file.

**Comment by tswapnil** [comment]
FrameLayout and ConstraintLayout have different package names.

**Comment by JeremySilverTongue** [comment]
This is expected behavior. ConstraintLayout needs its fully qualified package name, since it's not part of the framework yet. FrameLayout doesn't need the full name. I'll add a note to that effect on the exercise.

**Comment by yash10p** [comment]
'android.widget.FrameLayout' is the correct package name.

**Comment by JeremySilverTongue** [comment]
Added hint https://github.com/udacity/ud851-Exercises/commit/894c2390b600fe4bd4a2130017eed763a4998635
