### ISSUE TITLE
Errors in T04a.01-Exercise-AddNewActivity

### ISSUE THREAD

**Issue by Lunisce** [udacity/ud851-Exercises#132]
This project includes errors and also crashes Android Studio. More details in the comments section for the YouTube video that covers this project - https://youtu.be/-zRpQ-TDBPc

**Comment by snuffyTHEbear** [comment]
Having the same issues here as well: https://pastebin.com/Le71mEMg
Attempted to address the issues but having no success, even reinstalling Android Studio made no difference.

**Comment by johnshea** [comment]
Closing as I am unable to duplicate.

Dependencies have been updated. Please try again and open a new issue if it still occurs.
