### ISSUE TITLE
There isn’t anything to compare

### ISSUE THREAD

**Issue by beltyukov1** [udacity/ud851-Exercises#144]
Hi, after completing an exercise in the Udacity course, it provides a **Diff** option. However, branches don't seem to exist when doing compares.

Example compare URL: [https://github.com/udacity/ud851-Exercises/compare/T07.04-Exercise-UpdateTheAdapter...T07.04-Solution-UpdateTheAdapter](https://github.com/udacity/ud851-Exercises/compare/T07.04-Exercise-UpdateTheAdapter...T07.04-Solution-UpdateTheAdapter)

Above URL produces the following message: **There isn’t anything to compare.**

Could we get the branches restored to fix the issue? Thanks!

**Comment by e-xplore** [comment]
I am having same issue, I removed all my local files and downloaded updated files from git, but no luck. Still showing same error.

[https://github.com/udacity/ud851-Exercises/compare/T03.02-Exercise-ViewHolder...T03.02-Solution-ViewHolder](url)

**Comment by bumxu** [comment]
@assersamak, an accident? 😋
![captura de pantalla 2017-03-31 a las 19 18 05](https://cloud.githubusercontent.com/assets/1742635/24561405/ead4d250-1646-11e7-8a20-0d30fb9fbf73.png)

**Comment by egmp777** [comment]
Same IIssue. I am startijng T09 exercises, and when I try to compare I get There is Nothing to Compare

**Comment by artem-p** [comment]
Same thing with me.

**Comment by danmcmillen** [comment]
Also having this issue, as @beltyukov1 noted the branches used to compare were deleted.

**Comment by asamaka** [comment]
Thanks everyone for pointing this out!
Should be resolved now, sorry for the delay
