### ISSUE TITLE
Typo in 3.07

### ISSUE THREAD

**Issue by kliu99** [udacity/ud851-Exercises#16]
`// TODO (5) Implement OnClickListener in the ForecastAdapterViewHolder class
`
should be 
`// TODO (5) Implement OnClickListener in the NumberViewHolder
 class
`

-------------------

`
// TODO (6) Override onClick, passing the clicked item's position (getAdapterPosition()) to mClickHandler via its onListItemClick method
`
should be
`
// TODO (6) Override onClick, passing the clicked item's position (getAdapterPosition()) to mOnClickListener via its onListItemClick method
`

**Comment by ghost** [comment]
I second this.

**Comment by Ysix** [comment]
The typo is also present in the solution part.

**Comment by JeremySilverTongue** [comment]
Thanks! Fixed in https://github.com/udacity/ud851-Exercises/commit/0d988fb0047e08fd73fe0ecd4e3b92a91096b53e
