### ISSUE TITLE
fatal: unable to checkout working tree

### ISSUE THREAD

**Issue by 4sskick** [udacity/ud851-Exercises#160]
I've been checkout the repo using source tree, after some time it finished with some errors like "**unable to create file Lesson08-Quiz-Example/T08.01-Solution-AddTheContentProviderPermission/droidtermsprovider/src/main/java/com/udacity/example/droidtermsprovider/DroidTermsExampleContract.java: Filename too long**" and any other like that because of filename too long. After done to checkout there is fatal error said "**fatal: unable to checkout working tree**" and give a warning "**warning: Clone succeeded, but checkout failed.**"

**Comment by johnshea** [comment]
Resolved.
