### ISSUE TITLE
T08.03-Solution-FinishQuizExample is not running due to java.lang.NullPointerException:

### ISSUE THREAD

**Issue by kobyost** [udacity/ud851-Exercises#161]
The solution is not running and the app has stopped.
I think the cursor is null from some reason.

> ```
>  Process: com.udacity.example.quizexample, PID: 14289
>                                                    java.lang.NullPointerException: Attempt to invoke interface method 'int android.database.Cursor.getColumnIndex(java.lang.String)' on a null object reference
>                                                        at com.udacity.example.quizexample.MainActivity$WordFetchTask.onPostExecute(MainActivity.java:158)
>                                                        at com.udacity.example.quizexample.MainActivity$WordFetchTask.onPostExecute(MainActivity.java:136)
>                                                        at android.os.AsyncTask.finish(AsyncTask.java:660)
>                                                        at android.os.AsyncTask.-wrap1(AsyncTask.java)
>                                                        at 
> ```
Any one knows what is the problem and how to solve it?

**Comment by aritrabasu104** [comment]
Make sure u have downloaded [https://github.com/udacity/DroidTermsExample-APK/raw/master/droidtermsexample-release.apk](url) and installed it in the emulator(via drag drop or adb install filename from system tools dir in android install dir)
Do this before installing the quiz app. :)

**Comment by reachvineetjain** [comment]
For me the app worked on an actual device rather than the emulator. You need to have the  droidtermsexample-release.apk installed on the physical device before running your application.
And I still need to figure out why the app does not work for me on the emulator.

**Comment by johnshea** [comment]
Closing this issue as it is not related to the repo's code.

**Comment by mikemendizabal** [comment]
I have had my app crash too. CONTENT_AUTHORITY = "com.example.udacity.droidtermsexample"
It's a possibility the Internet dependency has closed down. Can I have CONTENT_AUTHORITY equal to something else so I can get something else to work?
