### ISSUE TITLE
T04b.02-Exercise-OpenMap - Intent data is now corrupted

### ISSUE THREAD

**Issue by rmarquis** [udacity/ud851-Exercises#163]
A bug as been introduced in commit a39d82badc0b5a388b043737de301f50247a71f5.

When adding a path in a Uri.Builder, a "/" is inserted before the string passed as parameter. 
The final URI is `geo:/0.0?q=1600 Amphitheater Parkway, CA` instead of `geo:0.0?q=1600 Amphitheater Parkway, CA`. As a result, the intent data can't be passed to the map application.

Thx to @ericcleao for finding the issue.

**Comment by johnshea** [comment]
Fixed.
