### ISSUE TITLE
T10.02 Vector drawables cannot be decoded into bitmaps.

### ISSUE THREAD

**Issue by Naetmul** [udacity/ud851-Exercises#169]
The `BitmapFactory.decodeResource()` function can only decode bitmap-like drawables.
Because the drawable `R.drawable.ic_local_drink_black_24px` is a vector xml drawable,
`BitmapFactory.decodeResource(res, R.drawable.ic_local_drink_black_24px)`
will always return `null`.
That is, the static method `NotificationUtils.largeIcon(Context)` will always return `null`.

You should use methods like the one in http://stackoverflow.com/questions/33696488/getting-bitmap-from-vector-drawable (using a canvas or so).

Alternatively, you can simply change the `R.drawable.ic_local_drink_black_24px` drawable to a PNG or JPEG (bitmap) file.

**Comment by johnshea** [comment]
Fixed.
