### ISSUE TITLE
bad gradle distribution url

### ISSUE THREAD

**Issue by alonn24** [udacity/ud851-Exercises#17]
gradle-wrapper.properties have;
distributionUrl=https\://services.gradle.org/distributions/gradle-3.2.1-all.zip
but the latest android studio support:
distributionUrl=https\://services.gradle.org/distributions/gradle-2.14.1-all.zip

should change it in the code or change settings -> build, Execution, Deployment -> Gradle mark "Use default gradle wrapper"

**Comment by star1989** [comment]
I got the same problem.

**Comment by JeremySilverTongue** [comment]
Both Gradle 3.2.1 and 3.3 are working for me on Android Studio 2.2.3. The documentation on the Android Gradle plugin advises

> The following table lists which version of Gradle is required for each version of the Android plugin for Gradle. For the best performance, you should use the latest possible version of both Gradle and the Android plugin.

I'm not sure why 3.2.1 isn't working for you. Unless there's something widespread going on here, I'm going to leave as is, periodically updating the wrapper (and Android plugin) to to the latest version.
