### ISSUE TITLE
T?.? progressbar overlaps json text after tapping search

### ISSUE THREAD

**Issue by sansha** [udacity/ud851-Exercises#175]
for me, after clicking search I have the progressbar overlapping the TextView, first "enter a text" and then the JSON text.

to fix this I just made the TextView mSearchResultsTextView Invisible onPreExecute.

@Override
        protected void onPreExecute() {
            mProgressBar.setVisibility(View.VISIBLE);
            mSearchResultsTextView.setVisibility(View.INVISIBLE);
        }

instead of 
@Override
        protected void onPreExecute() {
            mProgressBar.setVisibility(View.VISIBLE);
        }

**Comment by johnshea** [comment]
Cosmetic change to the UI behavior..

Not implementing at this time.
