### ISSUE TITLE
Cannot resolve symbol 'NetworkUtils' in DisplayUrl of Toy appp

### ISSUE THREAD

**Issue by DhruviGoyal** [udacity/ud851-Exercises#176]

**Comment by DhruviGoyal** [comment]
I am not able to build the project because android studio is showing error in  the following line:
URL githubSearchUrl = NetworkUtils.buildUrl(githubQuery);

This line is in the MainActivity.java in the following link:
https://github.com/udacity/ud851-Exercises/tree/student/Lesson02-GitHub-Repo-Search/T02.03-Exercise-DisplayUrl

**Comment by jwill** [comment]
We don't actively monitor this issue list enough to guarantee timely help. If you are enrolled in the Nanodegree program, I encourage you to consult a mentor. 

If you are enrolled in the free course, you can ask your question in the forums here: https://discussions.udacity.com/c/standalone-courses/developing-android-apps
