### ISSUE TITLE
Variable name inconsistency

### ISSUE THREAD

**Issue by bruj0** [udacity/ud851-Exercises#183]
The video at https://youtu.be/oL2Yl6lZrQM?t=1m41s creates a variable named "errorMessageTextView" but at https://youtu.be/oL2Yl6lZrQM?t=1m53s it uses mErrorMessageTextView

**Comment by jwill** [comment]
I understand that it can be frustrating at times for things to be inconsistent but the code in this repository is the source of truth and course code in videos might differ from time to time.

Thanks for the report. I hope you are enjoying the course otherwise.
