### ISSUE TITLE
T02.04-Solution - Github query has stopped.

### ISSUE THREAD

**Issue by watdeo** [udacity/ud851-Exercises#184]
I ran the exercise **T02.04-Solution-ConnectingToTheInternet**, and when I clicked search after typing in the searchbar, the program crashes with android avd telling me "Github query has stopped".

I am using the Pixel and Nexus 5X API 26 virtual devices.

**Comment by heriisei** [comment]
hello, maybe you forget to replace
`return null;` 
to
`return url;` 
on line 64.

**Comment by johnshea** [comment]
Closing this issue as it is not related to the repo's code.
