### ISSUE TITLE
Cannot resolve anything

### ISSUE THREAD

**Issue by jeddy99** [udacity/ud851-Exercises#188]
__I'm using android studio  2.3.2 and when I open the very first exercise project it's all red lines.it cannot resolve AppCompactActivity and every other thing.  I tried clearing cache and restarting  but that doesn't work either

**Comment by getsadzeg** [comment]
This is clearly not an issue of the project.

**Comment by johnshea** [comment]
Closing this issue as it is not related to the repo's code.
