### ISSUE TITLE
T10.01-Exercises-IntentServices

### ISSUE THREAD

**Issue by hendrawd** [udacity/ud851-Exercises#189]
There is a different of the method name from the TODOs, when i believe they refer to the same method

> TODO (6) Create a public static void method called **executeTask**

> TODO (13) Call ReminderTasks.**executeTaskForTag** and pass in the action to be performed

**Comment by hendrawd** [comment]
Created a pull request https://github.com/udacity/ud851-Exercises/pull/190

**Comment by johnshea** [comment]
Fixed.
