### ISSUE TITLE
T02.06 Add-Polish todo typos

### ISSUE THREAD

**Issue by Ajimi** [udacity/ud851-Exercises#19]
File name: activity_main.xml
TODO (11) Make this TextView a child of the FrameLayout **_the_** you added above
TODO (11) Make this TextView a child of the FrameLayout **_that_** you added above

**Comment by JeremySilverTongue** [comment]
Thanks! Fixed in https://github.com/udacity/ud851-Exercises/commit/33dd082a347f99ab4010d28ecd26a12bcc72f8c4
