### ISSUE TITLE
T10.04-Exercise-PeriodicSyncWithJobDispatcher -> Failed to resolve: com.firebase:firebase-jobdispatcher:0.7.0

### ISSUE THREAD

**Issue by Patilvivek28** [udacity/ud851-Exercises#192]
I tired using multiple versions of this repo, but every time it says like Failed to resolve.

I am using Android Studio v2.3.3 & my app details are like below :

android {
compileSdkVersion 25
buildToolsVersion "25.0.2"
defaultConfig {
applicationId "com.example.android.APP_NAME"
minSdkVersion 10
targetSdkVersion 25
versionCode 1
versionName "1.0"
}
buildTypes {
release {
minifyEnabled false
}
}
}

Please help me in getting this resolved ASAP.

**Comment by johnshea** [comment]
Closing this issue as it is not related to the repo's code.
