### ISSUE TITLE
XML Preview says "Rendering Problems"

### ISSUE THREAD

**Issue by oissa1** [udacity/ud851-Exercises#195]
When editing the activity XML files the preview on the right doesn't display properly and says "Rendering problems". This was resolved by editing the styles.xml file and changing "Theme.AppCompat.Light.DarkActionBar" to "Base.Theme.AppCompat.Light.DarkActionBar". Not sure why mine required that but I did see online that other people have had this issue so may need to be changed in the existing repo.

**Comment by OmarAbdelhafiz** [comment]
This is not a problem with the repo. I had this problem for a long time because I ignored `Android Studio`'s updates, `Build-Tools`' Updates, etc.

I recommend you to upgrade `Android Studio` to the latest version and any other updates `Android Studio` would notify you about.

**Comment by johnshea** [comment]
Closing this issue as it is not related to the repo's code.
