### ISSUE TITLE
T(all) - Update compileSdkVersion and buildToolsVersion to latest Version

### ISSUE THREAD

**Issue by OmarAbdelhafiz** [udacity/ud851-Exercises#199]
I think we should update the `compileSdkVersion`, `buildToolsVersion` and `targetSdkVersion` in the `build.gradle` (app) to the latest version, from the older Android Nougat `SDK Build-Tools 25.0.2`, `SDK Platform 25` and 25, to Android O, `SDK Build-Tools 26.0.1`, `SDK Platform 26` and 26.

Thanks in Advance.

Omar.

**Comment by johnshea** [comment]
Fixed.
