### ISSUE TITLE
T08.03-Exercises

### ISSUE THREAD

**Issue by kliu99** [udacity/ud851-Exercises#20]
Should add another TODO to override the `onDestory` method that close the cursor

``` java
@Override
protected void onDestroy() {
    super.onDestroy();
    // Don't forget to close your cursor!
    mData.close();
}
```

**Comment by JeremySilverTongue** [comment]
Good point! Fixed in https://github.com/udacity/ud851-Exercises/commit/8d3ba8fa77313502efe6401930b811a0a9708c5a
