### ISSUE TITLE
T04b.02-Solution-OpenMap query not working

### ISSUE THREAD

**Issue by fabiohxcx** [udacity/ud851-Exercises#201]
I had to replace ".query(addressString);" for ".appendQueryParameter("q",addressString);" in order to work it.

**Comment by arsyee** [comment]
Also builder.path("0,0") is not working, as it is sanitizing the comma. Should be used encodedPath("0,0") instead.
So what I believe is the correct solution:
        builder.scheme("geo")
                .encodedPath("0,0")
                .appendQueryParameter("q", addressString);

**Comment by arsyee** [comment]
Also this issue seems to be duplicate to: #70 #75 #118 #182 
And can be related to #163
So, dear Google, you might just want to solve all these in one go :-)

**Comment by keltroth** [comment]
By the way, the "Understanding URIs" and its quizz is also wrong about "query" part...

**Comment by johnshea** [comment]
Fixed.
