### ISSUE TITLE
T05a.03-FixLifecycleDisplayBug: Could replace adding/iterating backwards over list w/ forward version

### ISSUE THREAD

**Issue by croworc** [udacity/ud851-Exercises#208]
Hi y'all,
maybe I'm missing something here, but as to my understanding it might be more straightforward (no pun intended) to exchange the backward iteration in method `onCreate()` over the list of lifecycle events stored in the   `ArrayList<String>  mLifecycleCallbacks` with a forward version.

If you were to add these events in `onStop()` and `onDestroy()` simply to the **end** of the list instead of to the **beginning**, like:
  ```
          // COMPLETED (2) Add the ON_STOP String to mLifecycleCallbacks
        mLifecycleCallbacks.add(ON_STOP);
  
  ... and ...

          // COMPLETED (3) Add the ON_DESTROY String to mLifecycleCallbacks
        mLifecycleCallbacks.add(ON_DESTROY);
  ```
then you could simply iterate **forward** over your list of events and append them to the lifecycle TextView, like so:
  ```
        if (savedInstanceState != null) {
            if (savedInstanceState.containsKey(LIFECYCLE_CALLBACKS_TEXT_KEY)) {
                String allPreviousLifecycleCallbacks = savedInstanceState
                        .getString(LIFECYCLE_CALLBACKS_TEXT_KEY);
                mLifecycleDisplay.setText(allPreviousLifecycleCallbacks);
            }
        }

        // COMPLETED (4) Iterate through mLifecycleCallbacks, appending each String and
        // a newline to mLifecycleDisplay
        for (String eventString : mLifecycleCallbacks) {
            mLifecycleDisplay.append(eventString + "\n");
        }
  ```
Would be more brain-friendly to read; *not not-nice*, so to say.
Cheers, Ingo

**Comment by johnshea** [comment]
Thank you for your suggestion.
