### ISSUE TITLE
T06.05-PreferenceChangeListener: TODO (2) wording: "update property" vs. "update preference"

### ISSUE THREAD

**Issue by croworc** [udacity/ud851-Exercises#209]
TODO (2) currently reads:
`// TODO (2) Override the onSharedPreferenceChanged method and update the show bass preference`

What is required to be done though, is to update the VisualiserView's `showBass` property, via its `setShowBass(true/false)` method (and not the preference itself).

Maybe it's just splitting hairs, but anyway, I'd propose to change the wording to something like:
`// TODO (2) Override the onSharedPreferenceChanged method and update the VisualiserView's showBass property via its setShowBass(true/false) setter method.`

What do you think?
Kind regards,
Ingo

**Comment by johnshea** [comment]
Thank you for your input but we will not be changing this at this time.
