### ISSUE TITLE
T02.02-Exercise - wrong instruction

### ISSUE THREAD

**Issue by Tsien** [udacity/ud851-Exercises#210]
https://github.com/udacity/ud851-Exercises/blob/student/Lesson02-GitHub-Repo-Search/T02.02-Exercise-AddMenu/app/src/main/java/com/example/android/datafrominternet/MainActivity.java#L42

shouldn't it be `main.xml`?

**Comment by getsadzeg** [comment]
Yeah I think so too. It should be `main.xml`.

**Comment by johnshea** [comment]
Fixed.
