### ISSUE TITLE
T05b.03-Solution-PolishAsyncTask - ProgressBar staying visible

### ISSUE THREAD

**Issue by FerretAtTheCaret** [udacity/ud851-Exercises#211]
After leaving the app (e.g. going to the home screen) and opening it again,
the cached data is recovered properly avoiding the calls of both loadInBackground and onLoadFinished.
Since onLoadFinished is not called, there is however no line of code which sets the loading indicator's visibility to invisible again.

I suggest to modify some code within onStartLoading of the 
[MainActivity](https://github.com/udacity/ud851-Exercises/blob/student/Lesson05b-Smarter-GitHub-Repo-Search/T05b.03-Solution-PolishAsyncTask/app/src/main/java/com/example/android/asynctaskloader/MainActivity.java) .

I suggest moving line 184 inside of the else block starting in line 193 - thus the loading indicator will only even made visible in case onLoadFinished will be called later making it invisible again..

**Comment by johnshea** [comment]
Fixed.
