### ISSUE TITLE
T03.01 app's build.gradle is incorrect in Diff

### ISSUE THREAD

**Issue by NaturalBornCamper** [udacity/ud851-Exercises#215]
Solution [here ](https://github.com/udacity/ud851-Exercises/blob/student/Lesson03-Green-Recycler-View/T03.01-Solution-RecyclerViewLayout/app/build.gradle)says to use
compile 'com.android.support:recyclerview-v7:25.1.0'

However the [diff link](https://github.com/udacity/ud851-Sunshine/compare/S03.01-Exercise-RecyclerView...S03.01-Solution-RecyclerView) on [Lesson 3, page 9](https://classroom.udacity.com/courses/ud851/lessons/c81cb722-d20a-495a-83c6-6890a6142aac/concepts/1f679415-8a96-42c6-9880-7be8a15cee20) has a typo, using this incorrect dependency that causes a runtime exception:
compile 'com.android.support:recyclerview-v7:25.0.1'

**Comment by johnshea** [comment]
Fixed.

Dependencies have been updated.
