### ISSUE TITLE
T07.06 Remove guests - Illegal cursor error

### ISSUE THREAD

**Issue by dafm96** [udacity/ud851-Exercises#216]
java.lang.IllegalStateException: Couldn't read row 0, col -1 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.

**Comment by Raywilliams01** [comment]
@dafm96  I know its a little late but would you submit some sample code so I can see the error

**Comment by johnshea** [comment]
Closing.

Not enough information provided.
