### ISSUE TITLE
Error while executing T10.01-Exercise-IntentServices project

### ISSUE THREAD

**Issue by LordSomen** [udacity/ud851-Exercises#218]
![image](https://user-images.githubusercontent.com/29105619/32188144-e5ab660e-bd9e-11e7-91e5-19281bb01c76.png)
I fixed it in my code locally and will create PR if this issue is assigned to me

**Comment by olliejday** [comment]
Just need to add `vectorDrawables.useSupportLibrary = true` into the app gradle

**Comment by LordSomen** [comment]
Yeah we have to make very small change to solve this problem .....

**Comment by johnshea** [comment]
Fixed.
