### ISSUE TITLE
"IDE Error Occured" when adding a new Activity on Exercises projects after updating to Android Studio 3

### ISSUE THREAD

**Issue by NaturalBornCamper** [udacity/ud851-Exercises#226]
Can't add activities anymore, some config in the apps are wrong. New projects work fine but the udacity projects fail to add activities so it's impossible to progress in Chapter 4 when we work with intents. I tried migrating the Gradle plugin and checking out Google's migration video. Even posted on StackOverflow but no luck:
https://stackoverflow.com/questions/47165622/android-studio-ide-error-occured-on-create-new-activity

**Comment by ardanthir** [comment]
As CoastalB wrote on stackoverflow, commenting out os reference and adding google() repo in build.gradle  worked for me (You dont have to even change gradle plugin version)
allprojects {
    //String osName = System.getProperty("os.name").toLowerCase();
    //if (osName.contains("windows")) {
    //    buildDir = "C:/tmp/${rootProject.name}/${project.name}"
    //}
    repositories {
        google()
        jcenter()
    }
}

**Comment by petya0111** [comment]
You saved my solution, thanks!  @ardanthir

**Comment by RaghavMilind** [comment]
Thanks the solution worked for me ! @ardanthir

**Comment by johnshea** [comment]
Fixed.

Dependencies have been updated.

**Comment by NestorBurma1** [comment]
In my case I store all projects on disk D:
I have changed build.gradle(Project) line:
buildDir = "C:/tmp/${rootProject.name}/${project.name}"
to
buildDir = "D:/tmp/${rootProject.name}/${project.name}"
