### ISSUE TITLE
Project import issue

### ISSUE THREAD

**Issue by viktor1190** [udacity/ud851-Exercises#23]
On Adroid Studio 2.2.3 when I choose a folder Exercise (for example the 'T01.01-Exercise-CreateLayout'), and I try to import it from File menu -> Import project...   Android Studio shows a progress dialog but the project loading never ends, so I have to kill the application, create a empty project and copy/paste everything manually. Could be an Android studio incompatibility problem for old projects?. 

I appreciate all the effort you make to create these courses, they are very good, but this little detail makes the learning process a little tedious, I hope there is a solution for this. thank'u so much.

**Comment by croworc** [comment]
Hi @viktor1190 , have you tried the following:

Close any project(s) open in Android Studio, with 
    `File | Close Project`
and then, from within the `Welcome to Android Studio` assistant, choose 
    `Import Project (Eclipse ADT, Gradle, etc.)`

I'm using Android Studio 2.3 Beta1 on Linux and it imports correctly that way.
You might need to download the Build Tools version specified within the `app/build.gradle` file (if that version is missing in your installation), but in that case Android Studio will offer a link to do so.

If this shouldn't succeed, however, then maybe something is screwed up with your local clone / copy of the repo?!
In that case, you should probably start fresh w/ deleting your local project and repeating cloning the repo / downloading the ZIP.
Good luck,
Ingo

**Comment by ashwamegh** [comment]
Hi @viktor1190 , Try the solution as per @croworc  described.

And if it doesn't work, follow the same process by running your android studio as an Administrator. If further Gradle create issues with Constraint Layout library, then remove it from:

> **File>Project Structure>app>Dependencies**

.

Hope, this helps!
Shashank Shekhar

**Comment by viktor1190** [comment]
Hi guys, thanks for your replies. I solve it!.The problem was the Build Tools version, I checked the right version from the Github repository **"buildToolsVersion '25.0.1'"**  then I download it from the android sdk manager, and It is working really good. No matter if I import it from the welcome screen or file menu, only **be sure to get the right build tools version before import the project.**

By the way I am using windows 7, I do not know if this is the same in linux but surely can happen to someone else.

**Comment by kreativecoder** [comment]
Hi guys, I know this issue has been closed, but am still having this same problem. I have installed the "buildToolsVersion '25.0.1'" and "buildToolsVersion '25.0.2'". But its still not opening. I have tried all I could, someone should please help me.

**Comment by ashwamegh** [comment]
Have you tried importing it using Administrator privileges ?

**Comment by kreativecoder** [comment]
@shashank7200 , Yes I have

**Comment by ashwamegh** [comment]
@af-banjo  The problem has always been there with Android Studio during importing projects. Though, some users waited till 30 minutes & more with importing , may be this can help. Try your luck. :+1:

**Comment by kreativecoder** [comment]
@shashank7200 , Haven't tried the > 30mins path though. Let me try that. Thanks

**Comment by kreativecoder** [comment]
Patience solved it finally, thanks @shashank7200 for the help

**Comment by viktor1190** [comment]
I couldn't wait so long, next time try importing directly the gradle file "build.gradle" that is inside the project directory, this sometimes helps me to import it immediately.

**Comment by kreativecoder** [comment]
Thanks @viktor1190 , I will try that next time.
