### ISSUE TITLE
T01.02 Need to import android.widget.TextView;

### ISSUE THREAD

**Issue by LeeroyHannigan** [udacity/ud851-Exercises#232]
When I finished T01.02 my TextView variables were showing an error "symbol not found".
The issue was resolved by: import android.widget.TextView;
This may be an issue with my Android Studio, i'm not sure.

**Comment by wreed87** [comment]
Thanks for this, was driving me mad. Somehow it was not recognizing it either but it works now.

**Comment by johnshea** [comment]
Closing this issue as it is not related to the repo's code.
