### ISSUE TITLE
T02.06-Exercise-AddPolish

### ISSUE THREAD

**Issue by iperpin** [udacity/ud851-Exercises#235]
When you do a search and you try to do another search again, the progress bar appears in front of the text:

![screenshot_2017-11-14-21-02-59](https://user-images.githubusercontent.com/33392542/32803149-ea2d4266-c982-11e7-8997-8c39378db730.png)

This can be changed setting the text to empy String in the onPreExecute method:

` @Override
    protected void onPreExecute() {
        mSearchResultsTextView.setText("");
        mProgressBar.setVisibility(View.VISIBLE);
    }`

In my opinion the example gets more “polished”

**Comment by johnshea** [comment]
Closing as this is a UI design decision.
