### ISSUE TITLE
T(all): Build failure post Android Studio 3.0

### ISSUE THREAD

**Issue by sri-new** [udacity/ud851-Exercises#236]
I think it is time for an **overhaul of the exercise and sunshine codebase**. 

Android Studio 3.0 is a significant upgrade that warrants revising the codebase while still retaining all the compat goodness. I was successful in upgrading a couple of the exercises making it work with the newest 3.0.0 gradle plugin. However, doing this for each and every exercise is totally redundant. Further, it takes away a lot of time from learning and/or implementing the concept/component from the current lesson.

So, I believe that an upgraded exercises and sunshine codebase would not only help us but posterity as well.

**Comment by MaximoB** [comment]
Seconded, some toy apps need modifications to sync properly on the latest gradle plugin.

**Comment by vyomshah06** [comment]
How did you upgraded the gradle plugin for the exercises to work with android studio 3.0 and above?

**Comment by sri-new** [comment]
For AS 3.0.0, Gradle 4.1 or higher is required. Take a look at the below page.
https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration

**Comment by johnshea** [comment]
Fixed.
