### ISSUE TITLE
T05b.02 AddAsyncTaskLoader

### ISSUE THREAD

**Issue by howkymike** [udacity/ud851-Exercises#245]
minSdkVersion in build.gradle should be 11 or more.
Both in [Solution ](https://github.com/udacity/ud851-Exercises/blob/student/Lesson05b-Smarter-GitHub-Repo-Search/T05b.02-Solution-AddAsyncTaskLoader/app/build.gradle)and [Exercise](https://github.com/udacity/ud851-Exercises/blob/student/Lesson05b-Smarter-GitHub-Repo-Search/T05b.02-Solution-AddAsyncTaskLoader/app/build.gradle).

EDIT. Only if LoaderManager is implemented from android.content instead of android.support.v4.content

**Comment by johnshea** [comment]
Fixed.

Dependencies have been updated.
