### ISSUE TITLE
T10.05, T10.06 do not work on Android 4.4.4

### ISSUE THREAD

**Issue by alviksar** [udacity/ud851-Exercises#247]
There is a problem in T10.05-Solution-ChargingBroadcastReceiver and T10.06-Solution-StickyBroadcastForCharging (ud851, Lesson 11). Оn devices running platform versions lower than Android 5.0 vector drawables do not work properly and color does not change when you plug and unplug the device.

https://github.com/udacity/ud851-Exercises/pull/246

**Comment by johnshea** [comment]
Fixed.
