### ISSUE TITLE
Downloading fails....

### ISSUE THREAD

**Issue by danisharifmughal** [udacity/ud851-Exercises#252]
Hi,
I have a problem with downloading repository. when i start download i start like normal download but after some time i
![untitled](https://user-images.githubusercontent.com/34644739/34097457-02d112f6-e3fb-11e7-926d-dbcab2ffc970.png)
 gives error. Screen short attached.

**Comment by christianteshome** [comment]
I'm having trouble when i try to download Sunshine repository and the Toy App repository

**Comment by johnshea** [comment]
Closing this issue as it is not related to the repo's code.
