### ISSUE TITLE
T07.06-Exercise-RemoveGuests: delete method vulnerable to SQL Injection attacks

### ISSUE THREAD

**Issue by ramona-cristea** [udacity/ud851-Exercises#253]
Why in the exercise video the delete method is written in this way, forming the condition by concatenating the column name & the value instead of taking advantage of the parameterized statement via the use of string array like this:

`return mDb.delete(WaitlistContract.WaitlistEntry.TABLE_NAME, WaitlistContract.WaitlistEntry._ID + "=?", new String[] {String.valueOf(id)}) > 0;`

Please see the official description of the [delete](https://developer.android.com/reference/android/database/sqlite/SQLiteDatabase.html#delete1(java.lang.String, java.lang.String, java.lang.String[])) method.

By updating the database in this way (as presented in the exercise), isn’t the database vulnerable to SQL Injection attacks? Here we are somewhat safe because the value for id is not entered by user from an EditText. But what if we would’ve wanted to delete a guest by it’s name & the value for name would need to be entered by user himself?

Please check here more about SQL Injection attacks:
https://www.packtpub.com/books/content/knowing-sql-injection-attacks-and-securing-our-android-applications-them
http://www.informit.com/articles/article.aspx?p=2268753&seqNum=5

**Comment by johnshea** [comment]
In this scenario, it would not be vulnerable to an SQL injection attack. We (the programmer) are controlling what is being used in the SQL statement. The user is not entering information that is then concatenated.

As you noted, if we allow value(s) that the user enters then we would need to code defensively as described in https://developer.android.com/training/data-storage/sqlite#DeleteDbRow
