### ISSUE TITLE
 ud851-Exercises/Lesson11-Completeing-The-UI/T11.02-Exercise-DataBinding/app/build.gradle

### ISSUE THREAD

**Issue by calincan2000** [udacity/ud851-Exercises#254]
In order to avoid confusion please move comment
// TODO (1) Enable Data Binding in your application
from
dependencies {}
to
android {}

Thank You!

PS: Also in the lesson  "// TODO (1) Enable Data Binding in your application" is presented to be in android {}

**Comment by ghost** [comment]
[T11.02 - Exercise Data Binding](https://github.com/udacity/ud851-Exercises/issues/324)

**Comment by johnshea** [comment]
Fixed.
