### ISSUE TITLE
T06.04-Solution-UseResources

### ISSUE THREAD

**Issue by Ramyragabahmed** [udacity/ud851-Exercises#255]
Solution did not match with video.
Need to updated to  replace any hard coded value with the appropriate resource.
![t06-04-soloution](https://user-images.githubusercontent.com/33569135/34452808-37d1208c-ed50-11e7-96f4-5f7d718eea8f.PNG)

**Comment by filograno** [comment]
This issue  could be closed because does not exist.
Android Studio simply show you the values of the resources.
If you double click on each values (the green highlighted strings) Android Studio will show you what you expected.

**Comment by johnshea** [comment]
Not an issue as described above.
