### ISSUE TITLE
T08.03-Solution-FinishQuizExample - Possible CursorIndexOutOfBoundsException

### ISSUE THREAD

**Issue by ramona-cristea** [udacity/ud851-Exercises#260]
In the `nextWord` method first it checks if the cursor has been set. If it has, it tries to move the cursor to the next value, using `moveToNext` method. This will return false if it cannot, in which case, you call `moveToFirst` method to go back to the first row in the Cursor. But you never check the result for `moveToFirst` method. This method will return false if cursor is empty according to it's definition:

` *Move the cursor to the first row.

     *
     * <p>This method will return false if the cursor is empty.
     *
     * @return whether the move succeeded.
     */
     boolean moveToFirst(); `

If we call getString on an empty cursor, a `CursorIndexOutOfBoundsException` will be thrown and the app will crash. We should always check the result of `moveToFirst` method.

**Comment by johnshea** [comment]
Correct.

It is possible to throw an `CursorIndexOutOfBoundsException` as you described.

The result of `moveToFirst` should be checked and handled differently to avoid this exception.
