### ISSUE TITLE
Wrong use of "global" & "local" variable naming

### ISSUE THREAD

**Issue by ramona-cristea** [udacity/ud851-Exercises#261]
Through the lessons, when we are asked to create a member variable, sometimes it is referred to it as "local" variable & sometimes it is referred as "global" variable which is wrong & misleading. A variable can be called "global" in java only if it is declared as public static and can be accessed in all other classes of your project. A variable is local when is declared inside a method and is available only in that method. When we have to create a member variable, it should be called just like that "member variable". 
E.g. 

1. Member variable is referred as local variable:
T07.03-Exercise-GetAllTheData: TODO (8) in GuestListAdapter class- Add a new local variable mCount to store the count of items to be displayed in the recycler view
2. Member variable is referred as global variable:
T09.01-Solution-SetupContentProvider, T09.01-Exercise-SetupContentProvider
// [Hint] Declare the DbHelper as a global variable

**Comment by mamuleanu** [comment]
@ramona-cristea  I think that you should create a topic on the [forum](https://discussions.udacity.com/c/standalone-courses/ud851-emea) for this because this kind of problems (and others) are discussed there and I'm sure you will get a reply.

Also, 

> Member variable is referred as local variable:

I think that in this specific case (T07.03 TODO (8)) _local variable_ means  _private_

**Comment by ramona-cristea** [comment]
@mamuleanu there are already similar topics about this on the forum, that's why I didn't create an additional one. But I posted my findings, don't worry :). 
"I think that in this specific case (T07.03 TODO (8)) local variable means private"
Then why not calling it "a private member/instance variable". A local variable is totally something else. Should we guess what they mean by "global" or "local"?

**Comment by johnshea** [comment]
Closing this issue as it is not related to the repo's code.
