### ISSUE TITLE
T01.01-Exercise-CreateLayout Gradle build error

### ISSUE THREAD

**Issue by Sammiches327** [udacity/ud851-Exercises#264]
Just compiled the first exercise project, and found an issue that might arise for some people who aren't using their C drive on windows.

[Line 18](https://github.com/udacity/ud851-Exercises/blob/student/Lesson01-Favorite-Toys/T01.01-Exercise-CreateLayout/build.gradle#L18) of the root build.gradle file moves the build folder to a temporary location on the C drive, but for people who (like myself) don't use their C drive for projects, this causes a crash:

![output](https://user-images.githubusercontent.com/11577882/34801660-b110c7be-f61e-11e7-9b75-d6fa9872d213.PNG)

My solution is to either remove the if block entirely, so that the build folder just goes into the project folder, OR change the drive letter on line 18. You'll notice it starts with `C:\`, so just change that do whatever drive you're using. In my case, my secondary hard drive is `D`, so I changed it to `D:\`. Not really sure why this code is here in the first place, but just thought I'd post a solution if it confuses the newer students.

Android Studio info:
`Android Studio 3.0.1`
`Build #AI-171.4443003, built on November 9, 2017`
`JRE: 1.8.0_152-release-915-b01 amd64`
`JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o`
`Windows 10 10.0`

**Comment by Sammiches327** [comment]
This actually appears to be in all of the root project gradle files, so anyone having this issue just needs to change it per exercise.

**Comment by Madonahs** [comment]
I agree, i encountered this too.

**Comment by johnshea** [comment]
On Windows, normally the build directory is inside the project directory but this can cause issues when the file path maximum length is reached. This is a workaround for the situation.

https://stackoverflow.com/questions/33905687/error-file-path-too-long-on-windows-keep-below-240-characters

**Comment by Sammiches327** [comment]
@johnshea any reason why the file paths were explicitly defined? I've never seen that done in other projects I've contributed to. Is it somehow more efficient?
