### ISSUE TITLE
T02.03 Display Url

### ISSUE THREAD

**Issue by Smita07374** [udacity/ud851-Exercises#272]
When I am trying to run the application I am getting null pointer exception.
How can I resolve it.
What should I input in the EditText field to get the output.
And as per my understanding we are already creating the Url in Networking file and appending the input.Right?
Please help me in understanding this.  #176

**Comment by gersonlobos** [comment]
I believe you are supposed to get an error on that lesson. on the following lesson it explains why and ask you to create an async class.

**Comment by Smita07374** [comment]
It was because you have to return url in NetworkUtils class and i was returning null.

**Comment by Faydee1220** [comment]
Maybe you can check method buildUrl, if U forget to assign url with new value, U will get null.
```
URL url = null;
 try {
    url = new URL(builtUri.toString()); // Make sure U assign url with new value
} catch (MalformedURLException e) {
      e.printStackTrace();
}
```
or U can check full diff https://github.com/udacity/ud851-Exercises/compare/T02.03-Exercise-DisplayUrl...T02.03-Solution-DisplayUrl

**Comment by johnshea** [comment]
Closing this issue as it is not related to the repo's code.
