### ISSUE TITLE
SDK not found

### ISSUE THREAD

**Issue by gammaDeAvila** [udacity/ud851-Exercises#276]
Hi Everyone!

I have a problem importing the exercises in A.S 3.0.

The app throws me a gradle problem, and it says that SDK has not been found, but it is installed,
i'd be so much grateful if anyone could help me. 

<img width="1269" alt="captura de pantalla 2018-01-18 a la s 12 42 45" src="https://user-images.githubusercontent.com/31376496/35115226-1e0dfa7e-fc4d-11e7-9c02-75db7bfdcfe9.png">

**Comment by Paolo74** [comment]
I am having the same problem, but the sdk file are where they should be.
![schermata 2018-02-21 alle 22 55 55](https://user-images.githubusercontent.com/36714647/36507657-b84ff448-175a-11e8-96d8-dd039089ddd8.png)

thanks.

**Comment by johnshea** [comment]
Closing this issue as it is not related to the repo's code.
