### ISSUE TITLE
T06.04-Exercise-UseResources

### ISSUE THREAD

**Issue by LaQuay** [udacity/ud851-Exercises#291]
I think this comment is not very clear to someone that is not used to.

` <!-- TODO (2) Create a res->bools.xml file and create a boolean for this default value -->`

Because you should to set the bools.xml inside values folder, not directlly inside the res folder.

Something like this would be better:

` <!-- TODO (2) Create a res->values->bools.xml file and create a boolean for this default value -->`

**Comment by johnshea** [comment]
Thank you for your feedback but will not be changing at this time.
