### ISSUE TITLE
T03.02-Exercise-ViewHolder Extra Curly Bracket in GreenAdapter.java file

### ISSUE THREAD

**Issue by joshuapack** [udacity/ud851-Exercises#295]
https://github.com/udacity/ud851-Exercises/blob/639e34244a1c14aa6cc31eb7847b5c0b1d5da768/Lesson03-Green-Recycler-View/T03.02-Exercise-ViewHolder/app/src/main/java/com/example/android/recyclerview/GreenAdapter.java#L131

There looks to be an extra curly bracket on line 131.

**Comment by johnshea** [comment]
Fixed. Thank you.
