### ISSUE TITLE
T10.01-Exercise: Error:Execution failed for task ‘:app:mergeDebugResources’

### ISSUE THREAD

**Issue by user37112898** [udacity/ud851-Exercises#307]
In (Course: Developing android apps) ud851-Exercises/Lesson10-Hydration-Reminder/T10.01-Exercise-IntentServices/  Go to drawable and change the extension of images from .xml to .png to remove error.

**Comment by ghost** [comment]
[stackoverflow: Can't process attribute android:fillColor](https://stackoverflow.com/questions/46947008/updated-android-studio-to-3-0-and-getting-this-issue)

You just need to add the following line inside your default config of your app build.gradle:

```
defaultConfig{
       vectorDrawables.useSupportLibrary = true
    }
```

![screenshot of successful build](https://i.imgur.com/DmdPohu.png)

**Comment by Adithya188288** [comment]
Thank you

**Comment by johnshea** [comment]
Fixed.

**Comment by nipunaggarwal201** [comment]
not working

**Comment by codersguild** [comment]
Still Not Working
