### ISSUE TITLE
T10.01 Support of SDK Version 26

### ISSUE THREAD

**Issue by awkonecki** [udacity/ud851-Exercises#315]
When using SDK build version 26, exercise will throw errors due to lack of ability to process android:fillColor attributes within the drawable res folder.

Solution : 

Add `vectorDrawables.useSupportLibrary = true` under `defaultConfig` in the build.gradle file.

Under `Support Library` in 
[Android Developer Reference](https://developer.android.com/studio/write/vector-asset-studio.html)

**Comment by shawn-maybush** [comment]
Also update XML layouts to use android:srcCompat vs android:src attributes when identifying drawables.

**Comment by johnshea** [comment]
Fixed.
