### ISSUE TITLE
API Lvl 26+ issues with BatteryManager.isCharging() [T10.06]

### ISSUE THREAD

**Issue by shawn-maybush** [udacity/ud851-Exercises#320]
I logged batteryManager.isCharging() in onCreate and it always returned false in API 26 and API 27.

Worked as expected in 23.

Somewhere between API 23 and 26, BatteryManager.isCharging() broke. The code using the intentFilter and registerReceiver worked as expected in API lvl 26 and 27.

**Comment by johnshea** [comment]
Closing.

Dependencies have been updated to API 28. Android Gradle Plugin and gradle have also been updated.
