### ISSUE TITLE
ud851-Exercises/Lesson11-Completeing-The-UI/T11.02-Exercise-DataBinding Class member not generated

### ISSUE THREAD

**Issue by ghost** [udacity/ud851-Exercises#326]
[Stackoverflow](https://stackoverflow.com/questions/39483094/data-binding-class-not-generated)
[Stackoverflow solution](https://stackoverflow.com/a/44707001/1021364)

1. Move namespace from layout tag into ScrollView
2. Add empty data tag

Before
![Image of layout before change](https://i.imgur.com/H9HCIJL.png)
![Image of binding class before change](https://i.imgur.com/Ym0xTiO.png)

After
![Image of layout after change](https://i.imgur.com/gqrMCvF.png)
![Image of binding class after change](https://i.imgur.com/IBP2byS.png)

**Comment by johnshea** [comment]
No change - Unable to duplicate.
