### ISSUE TITLE
[T06.01-Exercise-SetupTheActivity]: TODO (3) needs fix

### ISSUE THREAD

**Issue by croworc** [udacity/ud851-Exercises#34]
TODO (3) in VisualizerActivity.java, starting at line 122, should be changed from:

> // TODO (3) In visualizer_menu.xml create a menu item with a single item. **The id and title
    // should be saved in strings.xml**, it should never be shown as an action,
    // orderInCategory should be 100  

to:

> // TODO (3) In visualizer_menu.xml create a menu item with a single item. **The id should be 
    // action_settings and the title should be saved in strings.xml**, 
    // it should never be shown as an action,
    // orderInCategory should be 100  

Kind regards,
ikrotzky

**Comment by JeremySilverTongue** [comment]
Fixed in https://github.com/udacity/ud851-Exercises/commit/ee9a66e2f8f7bc8df9413d5af8d2875a9cbd2fc9
