### ISSUE TITLE
T09: reset Loader Problem onResume _TodoListApp

### ISSUE THREAD

**Issue by pooriant** [udacity/ud851-Exercises#340]
There is a problem with onResume at Todo_listApp
when we are going to rotate our device . loader is going to reset itself and this is bad becuase we dont change anything and this is better to Loader just Load exist data and avoid to use our resource and memory 
i think its better to add a static boolean with false default value and check if we added new data recently then loader is going to reset but if just a rotate on our device . Load data from last query

this is udacity Code

 `@Override`
    `protected void onResume() {
        super.onResume();
        Log.i(TAG,"onResume");      
        getSupportLoaderManager().restartLoader(TASK_LOADER_ID, null, this);  }}`

and this is my offer

```
`public class MainActivity extends AppCompatActivity implements`
        `LoaderManager.LoaderCallbacks<Cursor> {`
    `private static final String TAG = MainActivity.class.getSimpleName();`

//at top of class a public global boolean
`public static boolean sItemChanged=false;`
```
.
.
.
//at onResume in MainAcitivty
 ```
@Override
    protected void onResume() {
        super.onResume();
        Log.i(TAG,"onResume");

        // re-queries for all tasks
        if (sItemChanged){
        getSupportLoaderManager().restartLoader(TASK_LOADER_ID, null, this);
        sItemChanged=false;
    }}
```

at AddTaskActivity
```

    public void onClickAddTask(View view) {

        String describeTask=((EditText)findViewById(R.id.editTextTaskDescription)).getText().toString();

        ContentValues contentValues=new ContentValues();
        contentValues.put(TaskContract.TaskEntry.COLUMN_DESCRIPTION,describeTask);
        contentValues.put(TaskContract.TaskEntry.COLUMN_PRIORITY,mPriority);

        Uri uriReturn=getContentResolver().insert(TaskContract.TaskEntry.CONTENT_URI,contentValues);

        Toast.makeText(this, "insert was successfull: "+uriReturn.toString(), Toast.LENGTH_SHORT).show();
 

//set boolean true from AddTaskACtivity
       MainActivity.sItemChanged=true;

        finish();}

```

**Comment by johnshea** [comment]
Closing this issue as it is not an issue but a proposal for a different coding design choice.
