### ISSUE TITLE
ud851-Exercises/Lesson06-Visualizer-Preferences/T06.01-Solution-SetupTheActivity/

### ISSUE THREAD

**Issue by nora-lu** [udacity/ud851-Exercises#341]
Is `return true;` missing from `onOptionsItemSelected` in the SettingsActivity when the menu item is `home`? Asking this because the official guide has the return statement: https://developer.android.com/training/implementing-navigation/ancestral.html#NavigateUp

**Comment by johnshea** [comment]
The code should have `return true;` since the event is consumed.
