### ISSUE TITLE
T(all): Update build.gradle files

### ISSUE THREAD

**Issue by wtsiamruk** [udacity/ud851-Exercises#344]
Each task requires reconfiguring a build, after Android Gradle plugin update. Is it possible to align all build files for the new Gradle plugin?

**Comment by rahul-raj** [comment]
Exactly, we need to spend extra time for this `everytime` when we import an exercise project. We had to replace `compile` with `implementation`, change the `compat version to 25.4.0` , plus we had to add `google maven repository` to the configuration. I really wonder if anybody really cares to update the files as I see several issues opened with no response :(

**Comment by wtsiamruk** [comment]
That's not a big deal of course, but, it's not a part of the exercises.

**Comment by JimmyCodes** [comment]
I believe its because at the time of creation for this course, the Android and gradle versions were what the exercises currently have.  
Android Studio IDE had some major updates since 2 years ago.  Thank you though you all helped me clear this up on my end.  I couldn't find the fix(es).

**Comment by johnshea** [comment]
Fixed.
