### ISSUE TITLE
T02.02 - Solution: Build Error: “No resource identifier found for attribute 'showAsAction' in package 'android'”

### ISSUE THREAD

**Issue by rodrigoror** [udacity/ud851-Exercises#348]
https://github.com/udacity/ud851-Exercises/blob/05cc7c2f3a6475297a1e69f8ba7862ec83e2337e/Lesson02-GitHub-Repo-Search/T02.02-Solution-AddMenu/app/src/main/res/menu/main.xml#L19

I did the following code to fix that, changing to:

xmlns:app="http://schemas.android.com/tools"

**Comment by johnshea** [comment]
Unable to duplicate.

Please provide additional details and steps to duplicate this issue if desired.
