### ISSUE TITLE
T01.01-Exercise-CreateLayout (Build.gradle) - Error

### ISSUE THREAD

**Issue by Lorioux** [udacity/ud851-Exercises#350]
defaultConfig {
        applicationId "com.android.example.favoritetoys"  //WRONG namespace
        //
        applicationId "com.example.android.favoritetoys"  //CORRECT namespace
    }

**Comment by johnshea** [comment]
Per the [Android Documentation - Set the application ID](https://developer.android.com/studio/build/application-id), the applicationId does not have to match your Java package name.
