### ISSUE TITLE
T02.05-Exercise-CreateAsyncTask

### ISSUE THREAD

**Issue by ngengesenior** [udacity/ud851-Exercises#352]
Running app on Android 4.4 with compileSdkVersion being 27 gives the following error

javax.net.ssl.SSLHandshakeException: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x6248d800: Failure in SSL library, usually a protocol error.

From my investigations, the ssl erro disappears when I switched to using a third party library(NetCipher) instead of HttpURLConnection.

**Comment by johnshea** [comment]
Sorry but we are unable to troubleshoot individual errors.
