### ISSUE TITLE
T01.02-Exercise-DisplayToyList -Can´t display toys

### ISSUE THREAD

**Issue by tomastermx** [udacity/ud851-Exercises#356]
I´m using android  studio version 3.1.2 and I tried  to solve  this excerise I can´t  display the toys, even I downloaded  the solution and I opened in the android studio and  also I couldn´t display  the toys

This is A new project I created from the scratch  copy and paste  the main activity of java and xml 

XML/////////////////////////////////////////////////
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/frameLayout"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".MainActivity">

    <TextView
        android:id="@+id/tv_toy_names"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:textAppearance="@style/TextAppearance.AppCompat"
        android:visibility="visible" />

</FrameLayout>

Mainactivity.java/////////////////////////////////////////

package com.example.tomaster.toy;

import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.widget.TextView;

public class MainActivity extends AppCompatActivity {

    private TextView  mToysListTextView;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

         mToysListTextView = findViewById(R.id.tv_toy_names);

        String[] toyNames = ToyBox.getToyNames();

        for(String toyName : toyNames) {
            mToysListTextView.append(toyName + "\n\n\n");
        }

    }
}
//////////////////////////////////////////////////////////////////////////////////

ToyBox/////////////////////////////////////////////////////////
package com.example.tomaster.toy;

public final class ToyBox {

        /**
         * This method returns a list of popular toy names from the 20th and early 21st centuries.
         * I don't know about you guys, but this definitely brings me back to my childhood...
         *
         * @return A list of popular toys
         */
        public static String[] getToyNames() {
            return new String[] {
                    "Red Toy Wagon",
                    "Chemistry Set",
                    "Yo-Yo",
                    "Pop-Up Book",
                    "Generic Uncopyrighted Mouse",
                    "Finger Paint",
                    "Sock Monkey",
                    "Microscope Set",
                    "Beach Ball",
                    "BB Gun",
                    "Green Soldiers",
                    "Bubbles",
                    "Spring Toy",
                    "Fortune Telling Ball",
                    "Plastic Connecting Blocks",
                    "Water Balloon",
                    "Paint-by-Numbers Kit",
                    "Tuber Head",
                    "Cool Ball with Holes in It",
                    "Toy Truck",
                    "Flying Disc",
                    "Two-Handed Pogo Stick",
                    "Toy Hoop",
                    "Dysmorphia Doll",
                    "Toy Train",
                    "Fake Vomit",
                    "Toy Telephone",
                    "Barrel of Primates",
                    "Remote Control Car",
                    "Square Puzzle Cube",
                    "Football",
                    "Intergalactic Electronic Phasers",
                    "Baby Horse Dolls",
                    "Machines that turn into other Machines",
                    "Teddy Bears",
                    "Shaved Ice Maker",
                    "Glow Stick",
                    "Squirt Guns",
                    "Miniature Replica Animals Stuffed with Beads that you swore to your parents would be worth lots of money one day",
                    "Creepy Gremlin Doll",
                    "Neodymium-Magnet Toy"
            };
        }

}

**Comment by johnshea** [comment]
Closing this issue as it is not related to the repo's code.

Confirming that T01.02-Solution code works correctly.
