### ISSUE TITLE
T03.07-Solution-RecyclerViewClickHandling - onListItemClick method notes

### ISSUE THREAD

**Issue by TheWiseOptimist** [udacity/ud851-Exercises#357]
In the comments is the following:
         * **Even if a Toast isn't showing, it's okay to cancel it.** Doing so
         * ensures that our new Toast will show immediately, rather than
         * being delayed while other pending Toasts are shown.

That is incorrect.  If you try mToast.cancel(); without checking that it exists, it will throw a Null Pointer Exception.

**Comment by johnshea** [comment]
No changes required.

The code in the solution checks if variable mToast is null before calling the code to cancel it.

The comment states if it is not `showing` not if it does not exists.
