### ISSUE TITLE
[T09.01-Exercise-SetupContentProvider]: Error on first exercise

### ISSUE THREAD

**Issue by DioMuller** [udacity/ud851-Exercises#36]
On Exercise: Data Design, the second question is:

**What is the variable for the column that contains the description of the task?**

Answering that question with the correct variable name (COLUMN_DESCRIPTION) gives me an error. The other two answers work as intended.

![captureud](https://cloud.githubusercontent.com/assets/4001166/21745860/ad3d5f3c-d51b-11e6-9958-08b01679bc76.PNG)

There are no spaces or other extra characters, the name was copied from the code.

**Comment by JeremySilverTongue** [comment]
Should be fixed. Please reopen if I messed something up: https://classroom.udacity.com/courses/ud851/lessons/88171055-d9e6-4da5-acc4-b92a302a75a8/concepts/ca7d0be2-c766-4547-bc5d-9e731a95ab9f#

**Comment by WKnak** [comment]
mine too. I'm trying COLUMN_DESCRIPTION with no success.
