### ISSUE TITLE
T.04b.02-Solution-OpenMap (Map does not open to the address)

### ISSUE THREAD

**Issue by monsur4** [udacity/ud851-Exercises#361]
When you run the code, the map does not open to the address.
This is because on line 50, the method onClickOpenAddressButton() is not written properly.
Within the method, lines 56-58 say:
builder.scheme("geo").path("0,0").query(addressString);
These lines should instead be written as: builder.scheme("geo").appendPath("0,0").appendQueryParameter("q", addressString);
This way, the map opens to the address.
It got me confused till I found the solution on StackOverflow.
Check this link https://stackoverflow.com/a/44222951

**Comment by DigitalSorceress** [comment]
Came here to say this... I thought I was doing something wrong.. Opened the solution and sure enough it was also doing the same thing... thanks for finding the appendQueryParameter Monsur4 as this was what I was looking for... works fine once I do that...   this is happening in both the MapView solution and the exercise (if one follows the video tutorial as it is wrong as well)

**Comment by hamidufalke** [comment]
Had the same issue, this fix the bug.

**Comment by cingh-jasdeep** [comment]
i confirm that solution by monsur4 works!

**Comment by johnshea** [comment]
Fixed.
