### ISSUE TITLE
Error loading the exercise in android studio

### ISSUE THREAD

**Issue by vyomshah06** [udacity/ud851-Exercises#364]
I am facing the error of plugins of android support when I open the file of exercise in android studio. So, can anyone help me out how to load the exercise in android studio?

**Comment by Praneet460** [comment]
Hello vyomshah06, Can you explain a little more about what type of error you are facing.

**Comment by JohnGJackson0** [comment]
Go to File--> Settings--> Plugins --> Enable Android Support

**Comment by johnshea** [comment]
Closing this issue as it is not related to the repo's code.
