### ISSUE TITLE
Unable to open these exercises directly from github to android studio

### ISSUE THREAD

**Issue by umairnsr87** [udacity/ud851-Exercises#366]
it is showing error that file not found when i am opening these files in android studio directly from github

**Comment by ghost** [comment]
Ok. You can follow the link from the udacity courses to download the zip files online. Lesson 2, 4th video has that link. Extract the files, then in your android studio, use file-open-project name, to access the required lesson. It should open seamlessly.

**Comment by JohnGJackson0** [comment]
What do you mean open the files directly from GitHub? You don't actually open anything from GitHub directly, what you do is use git to clone the repository to your computer. 
Download git 
Create GitHub account
Fork the repository to your account
CD into directory you want using a terminal or command prompt (ls to see files in directory)
Use Git Clone 'YOUR URL'
Open Exercise, Complete it
Git add . <-- add changes to the staging area
Git status <-- See the changes you are about to add 
git commit -m "Completed Exercise" <-- Commit the changes to your copy of the repository
git push origin student <-- upload it to your copy of the repository on GitHub.

Is this what you are doing? If not, you need to take the course on Git and Github like what was suggested at the start of the course.

**Comment by umairnsr87** [comment]
Yes my problem is resolved

**Comment by johnshea** [comment]
Closing this issue as it is not related to the repo's code.
