### ISSUE TITLE
[T07.02-Exercise-CreateTheDatabase]: TODO (3) needs fix

### ISSUE THREAD

**Issue by croworc** [udacity/ud851-Exercises#38]
The **TODO (3**) text should be changed 

**from:**

> Create a static final **String** called ...

**to:**

> Create a **private** static final **int** called ...

BTW: This should also be fixed in the [related course video](https://classroom.udacity.com/courses/ud851/lessons/b5ab398b-2d15-4840-b3ff-0171e84d1c8d/concepts/6394e715-add9-4ea0-ab87-fef77f51e08b#)  
Damned Copy&Paste...
:smile:

**Comment by JeremySilverTongue** [comment]
I think this was already fixed in https://github.com/udacity/ud851-Exercises/commit/055629c9ef62a8152ad53da6db6327b67257f2eb

Thanks for the report!
