### ISSUE TITLE
[T07.02-Solution-CreateTheDatabase]: COMPLETED (3) needs fix:

### ISSUE THREAD

**Issue by croworc** [udacity/ud851-Exercises#39]
The **COMPLETED (3)** text should be changed 

**from:**

> Create a static final **String** called ...

**to:**

> Create a **private** static final **int** called ...

links to issue #38

**Comment by JeremySilverTongue** [comment]
I think this was already fixed in https://github.com/udacity/ud851-Exercises/commit/055629c9ef62a8152ad53da6db6327b67257f2eb

Thanks for the report!
