### ISSUE TITLE
Exercise T02.03 Typo

### ISSUE THREAD

**Issue by mostafa07** [udacity/ud851-Exercises#393]
In the NetworkUtils class, there is a typo in the function buildURL() 's comment.
It should say Github server instead of the weather server.

/**
     * Builds the URL used to query Github.
     *
     * @param githubSearchQuery The keyword that will be queried for.
     * @return The URL to use to query the **weather** server.
     */
    public static URL buildUrl(String githubSearchQuery) {
        // TODO (1) Fill in this method to build the proper Github query URL
        return null;
    }

**Comment by johnshea** [comment]
Fixed.
