### ISSUE TITLE
[T03.02] Incorrect result of comparison between exercise branch and solution branch

### ISSUE THREAD

**Issue by tatsuyafujisaki** [udacity/ud851-Exercises#396]
Thank you for creating a great course. I might have found a minor issue.

# Expected result
The page https://github.com/udacity/ud851-Exercises/compare/T03.02-Exercise-ViewHolder...T03.02-Solution-ViewHolder detects (i.e. highlights) the implementations of COMPLETED (1), (2), ... (11).
```xml
<!-- COMPLETED (1) Create a layout resource in res/layout/ called number_list_item.xml-->
<!-- COMPLETED (2) Make the root layout a FrameLayout -->
<!-- COMPLETED (3) Make the width match_parent and the height wrap_content -->
<!-- COMPLETED (4) Set the padding to 16dp -->
<!-- COMPLETED (5) Add a TextView as the only child of the FrameLayout -->
<!-- COMPLETED (6) Give the TextView an ID "@+id/tv_item_number" -->
<!-- COMPLETED (7) Set the height and width to wrap_content -->
<!-- COMPLETED (8) Align the TextView to the start of the parent -->
<!-- COMPLETED (9) Center the TextView vertically in the layout -->
<!-- COMPLETED (10) Set the font family to monospace -->
<!-- COMPLETED (11) Set the text size to 42sp -->
```

# Actual result
The page https://github.com/udacity/ud851-Exercises/compare/T03.02-Exercise-ViewHolder...T03.02-Solution-ViewHolder does not detect (i.e. highlight) any implementaions of COMPLETED (1), (2), ... (11).

# Cause
The `T03.02-Exercise-ViewHolder` branch contains `number_list_item.xml`.

# Solution
Delete `number_list_item.xml` from `https://github.com/udacity/ud851-Exercises/blob/T03.02-Exercise-ViewHolder/app/src/main/res/layout/number_list_item.xml` because creating `number_list_item.xml` is part of the exercises.

**Comment by johnshea** [comment]
Fixed. Thank you.
