### ISSUE TITLE
Can't even properly open the lessons

### ISSUE THREAD

**Issue by ghost** [udacity/ud851-Exercises#399]
When I downloaded the zip files, unpacked them, and tried to open that on Android Studio, it gave me this error:

Error:Cannot create directory C:\tmp\T01.02-Exercise-DisplayToyList\app\intermediates\incremental\packageDebug\zip-cache

Nothing I tried to do works.  Can somebody give me a step by step solution?

**Comment by zedlabs** [comment]
make sure your disk has space where the project is being created else try creating in a different directory altogether.

**Comment by johnshea** [comment]
Closing this issue as it is not related to the repo's code.
