### ISSUE TITLE
Error:com.android.builder.internal.aapt.AaptException: Failed to crunch file 

### ISSUE THREAD

**Issue by jeonjuok** [udacity/ud851-Exercises#4]
Error:com.android.builder.internal.aapt.AaptException: Failed to crunch file C:\Users\jason\AndroidStudioProjects\ud851-Exercises-student\ud851-Exercises-student\Lesson01-Favorite-Toys\T01.01-Exercise-CreateLayout\app\build\intermediates\exploded-aar\com.android.support\appcompat-v7\24.1.1\res\drawable-hdpi-v4\abc_ic_star_half_black_48dp.png into C:\Users\jason\AndroidStudioProjects\ud851-Exercises-student\ud851-Exercises-student\Lesson01-Favorite-Toys\T01.01-Exercise-CreateLayout\app\build\intermediates\res\merged\debug\drawable-hdpi-v4\abc_ic_star_half_black_48dp.png

**Comment by RohanMenon** [comment]
http://stackoverflow.com/questions/30764604/execution-failed-for-task-appmergedebugresources-crunching-cruncher-png-fa

**Comment by aghalloran** [comment]
I believe the error is because the path name is greater than 240 characters. I fixed the problem by adding an option to the build.gradle project file "buildDir = "C:/tmp/${rootProject.name}/${project.name}"

http://stackoverflow.com/questions/39621250/how-to-fix-com-android-builder-internal-aapt-aaptexception-failed-to-crunch-fil

**Comment by arshcaria** [comment]
Again, the path character length limit.
Maybe that is one of the reasons why many developers turn to Mac.

**Comment by pattrickrice** [comment]
Go to build.gradle project file and the buildDir goes under the allprojects section

```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.3'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    buildDir = "C:/tmp/${rootProject.name}/${project.name}"
    repositories {
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

**Comment by JeremySilverTongue** [comment]
If anyone is watching this, I pushed what I think should be a fix to the lesson 2 exercises. Anyone want to give 'em a try?

**Comment by JeremySilverTongue** [comment]
Should be fixed by https://github.com/udacity/ud851-Exercises/commit/ca3e7db67b100f17a77532416225ef2838447760

**Comment by pattrickrice** [comment]
HI Jeremy, the problem seems fixed

**Comment by jalpesh** [comment]
Does this problem apply to mac?
