### ISSUE TITLE
T03.01-Exercise-RecyclerViewLayout

### ISSUE THREAD

**Issue by Ahmedmedhat187** [udacity/ud851-Exercises#403]
how to use getViewHolderBackgroundColorFromInstance in ColorUtils class to change he background color of the items in the RecyclerView.

**Comment by vstollen** [comment]
I know this doesn't quite answer your question, but I think in the first exercise the color isn't required to change. The solution also only has a white background color.

**Comment by zedlabs** [comment]
the color is an integer value you can create an int for the color and set it differently in your activity and add if statement to change it accordingly

**Comment by johnshea** [comment]
Closing this issue as it is not related to the repo's code.
