### ISSUE TITLE
[T12.03] Typo in TODO (2)

### ISSUE THREAD

**Issue by tatsuyafujisaki** [udacity/ud851-Exercises#405]
I suppose
```xml
<!-- TODO (2) Copy over the responsive_layout xml from the base layout folder -->
```
in [responsive_activity.xml](https://github.com/udacity/ud851-Exercises/blob/student/Lesson12-Visual-Polish/T12.03-Exercise-TabletLayout/app/src/main/res/layout-sw600dp/responsive_activity.xml) is a mistake for
```xml
<!-- TODO (2) Copy over the responsive_activity xml from the base layout folder -->
```

**Comment by johnshea** [comment]
Fixed.
