### ISSUE TITLE
T02.04-Solution-ConnectingToTheInternet (permission not explicitly required)

### ISSUE THREAD

**Issue by fernando-almeida** [udacity/ud851-Exercises#41]
Simply adding to AndroidManifest.xml 
<uses-permission android:name="android.permission.INTERNET" />
seems to not be enough to be able to make a request.

The only way I got this to work was to add the following code prior to calling the getResponseFromHttpUrl method
StrictMode.ThreadPolicy policy = new StrictMode.ThreadPolicy.Builder().permitAll().build();            StrictMode.setThreadPolicy(policy);

I didn't see this issue reported and this was the only way I got the request to return results, otherwise an error would be thrown.
android.os.NetworkOnMainThreadException at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1273)
Please advise on the best way to proceed regarding this issue.

**Comment by JeremySilverTongue** [comment]
This is actually the expected behavior for this exercise. The next exercise shows how to get the networking onto a background thread.
