### ISSUE TITLE
failed to open zip fille.

### ISSUE THREAD

**Issue by Monsteryogi** [udacity/ud851-Exercises#418]
Failed to open zip file.
Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
Re-download dependencies and sync project (requires network)
Re-download dependencies and sync project (requires network)

I am using android studio 3.2.+
and I am connected to the network even though it throws the error while building

**Comment by joshi98kishan** [comment]
i am facing the same problem.

**Comment by ghost** [comment]
Next time you may want to use the Restart and invalidate option of Android Studio. It clears out previous cache and download new gradle files.

**Comment by ahmedmed7t** [comment]
i have the same problem, any one can help me??
@Ogbitse  
@joshi98kishan 
@Monsteryogi

**Comment by johnshea** [comment]
Closing this issue as it is not related to the repo's code.
