### ISSUE TITLE
[T02.02-Solution-AddMenu]: Do 2 - 7 in menu.xml

### ISSUE THREAD

**Issue by ChrisKruegerDev** [udacity/ud851-Exercises#42]
The instruction in `MainActivity.java ` is confusing with the first and last description line **Do 2 - 7 in menu.xml**. It should be changed to **Do 2 - 7 in main.xml**.

    // Do 2 - 7 in menu.xml ///////////////////////////////////////////////////////////////////////
    // TODO (2) Create a menu in xml called main.xml
    // TODO (3) Add one menu item to your menu
    // TODO (4) Give the menu item an id of @+id/action_search
    // TODO (5) Set the orderInCategory to 1
    // TODO (6) Show this item if there is room (use app:showAsAction, not android:showAsAction)
    // TODO (7) Set the title to the search string ("Search") from strings.xml
    // Do 2 - 7 in menu.xml ///////////////////////////////////////////////////////////////////////

**Comment by JeremySilverTongue** [comment]
I know this notation isn't the best, but the intent is that everything between the 

    // Do 2 - 7 in menu.xml ///////////////////////////////////////////////////////////////////////

Lines is to be done in menu.xml.
