### ISSUE TITLE
T01.01 Could not find com.android.tools:common:25.2.3. Solution

### ISSUE THREAD

**Issue by DavyGuedes** [udacity/ud851-Exercises#428]
Hi. I am not able to compile the source code of T01.01-Exercise-CreateLayout
> Could not find com.android.tools:common:25.2.3.
Searched in the following locations:
    https://jcenter.bintray.com/com/android/tools/common/25.2.3/common-25.2.3.pom
    https://jcenter.bintray.com/com/android/tools/common/25.2.3/common-25.2.3.jar
Required by:
    project : > com.android.tools.build:gradle:2.2.3 > com.android.tools.build:gradle-core:2.2.3 > com.android.tools.build:builder:2.2.3
    project : > com.android.tools.build:gradle:2.2.3 > com.android.tools.build:gradle-core:2.2.3 > com.android.tools.build:builder:2.2.3 > com.android.tools.build:manifest-merger:25.2.3
    project : > com.android.tools.build:gradle:2.2.3 > com.android.tools.build:gradle-core:2.2.3 > com.android.tools.build:builder:2.2.3 > com.android.tools.ddms:ddmlib:25.2.3
    project : > com.android.tools.build:gradle:2.2.3 > com.android.tools.build:gradle-core:2.2.3 > com.android.tools.build:builder:2.2.3 > com.android.tools.analytics-library:shared:25.2.3
    project : > com.android.tools.build:gradle:2.2.3 > com.android.tools.build:gradle-core:2.2.3 > com.android.tools.build:builder:2.2.3 > com.android.tools.analytics-library:tracker:25.2.3
    project : > com.android.tools.build:gradle:2.2.3 > com.android.tools.build:gradle-core:2.2.3 > com.android.tools.build:builder:2.2.3 > com.android.tools:sdklib:25.2.3 > com.android.tools.layoutlib:layoutlib-api:25.2.3
    project : > com.android.tools.build:gradle:2.2.3 > com.android.tools.build:gradle-core:2.2.3 > com.android.tools.build:builder:2.2.3 > com.android.tools:sdklib:25.2.3 > com.android.tools:dvlib:25.2.3
    project : > com.android.tools.build:gradle:2.2.3 > com.android.tools.build:gradle-core:2.2.3 > com.android.tools.build:builder:2.2.3 > com.android.tools:sdklib:25.2.3 > com.android.tools:repository:25.2.3

 Searching on stackoverflow, I found someone with the same problem, and his solution works. This could be caused by a deletion of the 25.2.3 jar/pom resource from the jcenter repository,  resulting in 404.
> I had same problem. Someone has removed the 25.2.3 jar/pom from jcenter repository.
I did a temporary fix by using gradle 3.1.4 instead of 2.2.3 and adding google() to the repository as below:...
[https://stackoverflow.com/questions/53678786/could-not-find-com-android-toolscommon25-2-3#answer-53681045](url)

**Comment by phoenix377** [comment]
You can solve it by adding following code in app/build.gradle (at the same level of settings.gradle) until the gradle classpath of the library get updated.

```
subprojects { project =>
    if (project.name.contains('react-native-android-keyboard-adjust')) {
        buildscript {
            repositories {
                google()
                jcenter()
            }

            dependencies {
                classpath 'com.android.tools.build:gradle:3.1.4'
            }
        }
    }
}
```

**Comment by johnshea** [comment]
Could not duplicate.

NOTE - Dependencies have been updated. Please try again.
