### ISSUE TITLE
error in cloning project

### ISSUE THREAD

**Issue by Ahmedalsa** [udacity/ud851-Exercises#433]
I keep getting this error every time I try to import this project to Android Studio.
the error states: Unregistered VCS root detected.
![android2](https://user-images.githubusercontent.com/42217218/51056497-15980a80-15f4-11e9-9103-5120ad10009d.PNG)
![android1](https://user-images.githubusercontent.com/42217218/51056496-15980a80-15f4-11e9-844c-564f1ccc9cb6.PNG)
could someone please help me?

**Comment by Ahmedalsa** [comment]
I also get this error sometimes:
SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

**Comment by johnshea** [comment]
Closing this issue as it is not related to the repo's code.

**Comment by Ahmedalsa** [comment]
> Closing this issue as it is not related to the repo's code.
what does that mean?
can you help me with this issue?
