### ISSUE TITLE
T05a.03-FixLifecycleDisplayBug: optimize the code

### ISSUE THREAD

**Issue by yrickwong** [udacity/ud851-Exercises#435]
`` if (savedInstanceState != null) {
            if (savedInstanceState.containsKey(LIFECYCLE_CALLBACKS_TEXT_KEY)) {
                String savedContent = (String) savedInstanceState.get(LIFECYCLE_CALLBACKS_TEXT_KEY);
                mLifecycleDisplay.setText(savedContent);
            }
            //this code for show onStop and onDestroy
            for (int i = sLifecycleCallbacks.size() - 1; i >= 0; i--) {
                mLifecycleDisplay.append(sLifecycleCallbacks.get(i) + "\n");
            }
       }

**Comment by yrickwong** [comment]
I think it is more appropriate to put the code here.

**Comment by johnshea** [comment]
Thank you for your suggestion. We will take it under consideration.
