### ISSUE TITLE
Not able to access gradle files.

### ISSUE THREAD

**Issue by hkrynicki** [udacity/ud851-Exercises#436]
Projects are listed in a very weird manner, I am not able to see any gradle files. 

![image](https://user-images.githubusercontent.com/46712313/51344345-567a9e00-1a90-11e9-9c04-4bab8e668a30.png)

**Comment by Devil2020** [comment]
I think you Opened an directory that it have a lot of projects , So each project have an Android , android Test , So it override it by [1,2,.............]
>> The Answer {  Choose a specific project  }

**Comment by hkrynicki** [comment]
Yea, but when I change a view form Project to Project Source Files I am not able to see any files at all, I know its a bit silly question, but how would you open it like step by step? Lets assume that I downloaded archive to my hard drive.

**Comment by Devil2020** [comment]
1- Unzip this archive (it will extract a folder that have some projects )
2- Go and open Android Studio , Press on "Open an exist Project".
3- go to the directory that you unziped it , Select an Specific project to open

**Comment by hkrynicki** [comment]
Thanks, it looks like every time I tried to open all of them paralelly, at once, I am more used to visual studio where many projects can coexist in one solution. Opening one project at a time solved my problems.
