### ISSUE TITLE
Comment description is not correct  in NetworkUtils buildUrl function

### ISSUE THREAD

**Issue by girmamamuyeyilma** [udacity/ud851-Exercises#45]
https://github.com/udacity/ud851-Exercises/blob/student/Lesson02-GitHub-Repo-Search/T02.04-Exercise-ConnectingToTheInternet/app/src/main/java/com/example/android/datafrominternet/utilities/NetworkUtils.java

In the NetworkUtilit.java class 

 *** Builds the URL used to query Github.
     *
     * @param githubSearchQuery The keyword that will be queried for.
     * @return The URL to use to query the weather server.(the return value for this case is not the url for the weather server it is for the gitHub )
     */**
    public static URL buildUrl(String githubSearchQuery) {
        Uri builtUri = Uri.parse(GITHUB_BASE_URL).buildUpon()
                .appendQueryParameter(PARAM_QUERY, githubSearchQuery)
                .appendQueryParameter(PARAM_SORT, sortBy)
                .build();

        URL url = null;
        try {
            url = new URL(builtUri.toString());
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }

        return url;
    }

**Comment by JeremySilverTongue** [comment]
Thanks! Can you tell we stole those network utils from Sunshine :P

**Comment by girmamamuyeyilma** [comment]
That is what i guessed 👍 you are welcome!
