### ISSUE TITLE
T05a.03 TODO 1 description not complete

### ISSUE THREAD

**Issue by BakonJarser** [udacity/ud851-Exercises#46]
The first TODO in T05a.03 reads:
    // TODO (1) Declare and instantiate an ArrayList of Strings called mLifecycleCallbacks
It should read:
    // TODO (1) Declare and instantiate a static ArrayList of Strings called mLifecycleCallbacks
This code doesn't work if the ArrayList isn't static.

**Comment by JeremySilverTongue** [comment]
Good point! Fixed in https://github.com/udacity/ud851-Exercises/commit/0da96dbc19196ce21eed44b141e3fa6b6f0f34dc
