### ISSUE TITLE
T03.01-Exercise-RecyclerViewLayout - conflicting name between Main activity and xml rescources

### ISSUE THREAD

**Issue by morallito** [udacity/ud851-Exercises#468]
I'm having problems to see the resolution of this exercice. 

```
        int layoutIdForListItem = R.layout.number_list_item;
                                          ^
  symbol:   variable number_list_item

```

I'm getting this error and I have no Idea how to solve it. It looks like a file called number_list_item is missing inside the floder layout.

**Comment by eitanrab** [comment]
unsubscribe

**Comment by LaszloLajosT** [comment]
It happens because "number_list_item.xml" file doesn't exist yet.  Just make the changes and move on to the next task (exercise) where you will create it. 
(I assume you already figured it out.)

**Comment by Sagar0-0** [comment]
`<view class="android.support.v7.app.AlertController$RecycleListView"
        android:id="@+id/rv_numbers"
        android:layout_width="match_parent"
        android:layout_height="match_parent"/>`
