### ISSUE TITLE
No Lesson01-Favorite-Toys/T01.02-Exercise-DisplayToyList

### ISSUE THREAD

**Issue by bekicot** [udacity/ud851-Exercises#6]
Hello,
I'm following the guides from https://classroom.udacity.com/courses/ud851/lessons/93affc67-3f0b-4f9b-b3a4-a7a26f241a86/concepts/ebe17315-13a6-452b-828e-aa3de89c4c09#
and quite surprised that this repository have different folder count.

There is No Lesson01-Favorite-Toys/T01.02-Exercise-DisplayToyList

**Comment by sidewalkjoe** [comment]
Having the same issue. The folder does not exist on GitHub at the moment.

**Comment by francisco-gamonal** [comment]
+1

**Comment by beanolar** [comment]
+2 ;)

**Comment by beanolar** [comment]
Looks like it was deleted on Nov 9. Wonder if something was wrong w it. 
https://github.com/udacity/ud851-Exercises/commit/09fa407c258dc0244664bb82940533a49b329874

I'm going to try to download the last version ->
https://github.com/udacity/ud851-Exercises/tree/f345ac9bca34c32765691631609868654c532f2f/Lesson01-Favorite-Toys/T01.02-Exercise-DisplayToyList

**Comment by wanderingeek** [comment]
+1

**Comment by JeremySilverTongue** [comment]
Ugh, sorry. That's my bad. Will fix shortly. Rebasing is hard...

**Comment by JeremySilverTongue** [comment]
Fixed in c540ad3674c12dbe308ccf0bc1a279fcc6633c03
