### ISSUE TITLE
S03.01-Exercise-RecyclerView Diff

### ISSUE THREAD

**Issue by btamimi** [udacity/ud851-Exercises#64]
Hello,
I'm following the guide from "[Exercise: Create a RecyclerView](https://classroom.udacity.com/courses/ud851/lessons/c81cb722-d20a-495a-83c6-6890a6142aac/concepts/367dc8f7-4639-4650-8468-b08717a69e84#)" and the Diff link opens a Compare Changes page that display the following message:
"There isn’t anything to compare.
We couldn’t figure out how to compare these references, do they point to valid commits?"
Attached a screenshot of the issue ...

Thanks for your time and efforts

![diff](https://cloud.githubusercontent.com/assets/17100768/22512975/6938380c-e8a3-11e6-9999-dbbcca2831db.PNG)

**Comment by johnshea** [comment]
Checked and confirmed the link in the lesson shows the correct diff.
