### ISSUE TITLE
Can't create new empty activity

### ISSUE THREAD

**Issue by CosmicBoris** [udacity/ud851-Exercises#67]
In T06.01-Exercise-SetupTheActivity
 TODO 1 create new SettingsActivity, Android Studio reports error when I click finish button on new activity window, new Activity Dialog not closing (I can move it but not close it).
It happens only with projects from this repo, no problems while creating new activity's in my projects.

I got all latest tools from stable channel.   

IDE adds over 2000 lines off error message to log file 
here some of them:

2017-02-05 02:26:44,053 [  85794]   WARN - rendering.ConfigurationMatcher - 'default' is not a best match for any device/locale combination for file://X:/ud851-Exercises-student/Lesson06-Visualizer-Preferences/T06.01-Exercise-SetupTheActivity/app/src/main/AndroidManifest.xml.
Displaying it with
  , , , Left To Right, sw384dp, w384dp, h640dp, Normal Screen, Short screen aspect ratio, Not Round screen, Portrait Orientation, Normal, Day time, X-High Density, Finger-based touchscreen, Soft keyboard, No keyboard, Hidden navigation, No navigation, Screen resolution 1280x768, API Level 25
which is compatible, but will actually be displayed with another more specific version of the layout. 
2017-02-05 02:26:44,055 [  85796]   WARN - rendering.ConfigurationMatcher - 'default' is not a best match for any device/locale combination for file://X:/ud851-Exercises-student/Lesson06-Visualizer-Preferences/T06.01-Exercise-SetupTheActivity/.idea/misc.xml.
Displaying it with
  , , , Left To Right, sw384dp, w384dp, h640dp, Normal Screen, Short screen aspect ratio, Not Round screen, Portrait Orientation, Normal, Day time, X-High Density, Finger-based touchscreen, Soft keyboard, No keyboard, Hidden navigation, No navigation, Screen resolution 1280x768, API Level 25
which is compatible, but will actually be displayed with another more specific version of the layout. 
2017-02-05 02:26:44,079 [  85820]  ERROR -             freemarker.runtime - Error executing FreeMarker template 
FreeMarker template error:
The following has evaluated to null or missing:
==> manifestDir  [in template "root://activities/common/common_globals.xml.ftl" at line 26, column 39]

Tip: If the failing expression is known to be legally null/missing, either specify a default value with myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthessis: (myOptionVar.foo)!myDefault, (myOptionVar.foo)??

The failing instruction (FTL stack trace):
----------
==> ${manifestDir}  [in template "root://activities/common/common_globals.xml.ftl" at line 26, column 37]
    #include "../common/common_globals.xm...  [in template "root://activities/EmptyActivity/globals.xml.ftl" at line 8, column 5]
----------

Java stack trace (for programmers):
----------
freemarker.core.InvalidReferenceException: [... Exception message was already printed; see it above ...]
	at freemarker.core.InvalidReferenceException.getInstance(InvalidReferenceException.java:98)

...................................................

2017-02-05 02:26:44,092 [  85833]  ERROR - llij.ide.plugins.PluginManager - com.android.tools.idea.templates.FreemarkerUtils$TemplateProcessingException: freemarker.core.InvalidReferenceException: The following has evaluated to null or missing:
==> manifestDir  [in template "root://activities/common/common_globals.xml.ftl" at line 26, column 39]

Tip: If the failing expression is known to be legally null/missing, either specify a default value with myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthessis: (myOptionVar.foo)!myDefault, (myOptionVar.foo)??

The failing instruction (print stack trace for 1 more):
==> ${manifestDir}  [in template "root://activities/common/common_globals.xml.ftl" at line 26, column 37] 
java.lang.RuntimeException: com.android.tools.idea.templates.FreemarkerUtils$TemplateProcessingException: freemarker.core.InvalidReferenceException: The following has evaluated to null or missing:
==> manifestDir  [in template "root://activities/common/common_globals.xml.ftl" at line 26, column 39]

Tip: If the failing expression is known to be legally null/missing, either specify a default value with myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthessis: (myOptionVar.foo)!myDefault, (myOptionVar.foo)??

The failing instruction (print stack trace for 1 more):
==> ${manifestDir}  [in template "root://activities/common/common_globals.xml.ftl" at line 26, column 37]

Caused by: com.android.tools.idea.templates.FreemarkerUtils$TemplateProcessingException: freemarker.core.InvalidReferenceException: The following has evaluated to null or missing:
==> manifestDir  [in template "root://activities/common/common_globals.xml.ftl" at line 26, column 39]

Tip: If the failing expression is known to be legally null/missing, either specify a default value with myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthessis: (myOptionVar.foo)!myDefault, (myOptionVar.foo)??

The failing instruction (print stack trace for 1 more):
==> ${manifestDir}  [in template "root://activities/common/common_globals.xml.ftl" at line 26, column 37]

.......................................

Caused by: freemarker.core.InvalidReferenceException: The following has evaluated to null or missing:
==> manifestDir  [in template "root://activities/common/common_globals.xml.ftl" at line 26, column 39]

Tip: If the failing expression is known to be legally null/missing, either specify a default value with myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthessis: (myOptionVar.foo)!myDefault, (myOptionVar.foo)??

The failing instruction (print stack trace for 1 more):
==> ${manifestDir}  [in template "root://activities/common/common_globals.xml.ftl" at line 26, column 37]

.................................

2017-02-05 02:26:44,095 [  85836]  ERROR - llij.ide.plugins.PluginManager - Android Studio 2.2.3  Build #AI-145.3537739 
2017-02-05 02:26:44,095 [  85836]  ERROR - llij.ide.plugins.PluginManager - JDK: 1.8.0_76-release 
2017-02-05 02:26:44,096 [  85837]  ERROR - llij.ide.plugins.PluginManager - VM: OpenJDK 64-Bit Server VM 
2017-02-05 02:26:44,096 [  85837]  ERROR - llij.ide.plugins.PluginManager - Vendor: JetBrains s.r.o 
2017-02-05 02:26:44,096 [  85837]  ERROR - llij.ide.plugins.PluginManager - OS: Windows 10 
2017-02-05 02:26:44,096 [  85837]  ERROR - llij.ide.plugins.PluginManager - Last Action: template.create.ActivityEmpty Activity

**Comment by arshcaria** [comment]
Similar issue also reported here, 
https://github.com/udacity/ud851-Sunshine/issues/24
and here,
https://code.google.com/p/android/issues/detail?id=232076

**Comment by arshcaria** [comment]
btw, removing the build folder redirect  code in the gradle file is a workaround.

```
allprojects {
    //String osName = System.getProperty("os.name").toLowerCase();
    //if (osName.contains("windows")) {
    //    buildDir = "C:/tmp/${rootProject.name}/${project.name}"
    //}
    repositories {
        jcenter()
    }
}
```

**Comment by CosmicBoris** [comment]
Thanks arshcaria!

**Comment by arshcaria** [comment]
Well... You should not have closed this issue. This may be a bug of Android Studio or Android gradle build tool. It also causes other issues such as not able to resolve some symbols (the R resources class or even library classes).

**Comment by arshcaria** [comment]
Furthermore, in some ud851 projects, you cannot comment out / delete the redirect gradle code. If you do so in those projects, you are very likely to encounter build errors like below:

```
Error:Failed to crunch file D:\Devel\GitHub\ud851-Exercises\Lesson05b-Smarter-GitHub-Repo-Search\T05b.02-Exercise-AddAsyncTaskLoader\app\build\intermediates\exploded-aar\com.android.support\appcompat-v7\25.1.1\res\drawable-hdpi-v4\abc_textfield_search_default_mtrl_alpha.9.png into D:\Devel\GitHub\ud851-Exercises\Lesson05b-Smarter-GitHub-Repo-Search\T05b.02-Exercise-AddAsyncTaskLoader\app\build\intermediates\res\merged\debug\drawable-hdpi-v4\abc_textfield_search_default_mtrl_alpha.9.png
Error:Execution failed for task ':app:mergeDebugResources'.
> Error: Failed to crunch file D:\Devel\GitHub\ud851-Exercises\Lesson05b-Smarter-GitHub-Repo-Search\T05b.02-Exercise-AddAsyncTaskLoader\app\build\intermediates\exploded-aar\com.android.support\appcompat-v7\25.1.1\res\drawable-hdpi-v4\abc_textfield_search_default_mtrl_alpha.9.png into D:\Devel\GitHub\ud851-Exercises\Lesson05b-Smarter-GitHub-Repo-Search\T05b.02-Exercise-AddAsyncTaskLoader\app\build\intermediates\res\merged\debug\drawable-hdpi-v4\abc_textfield_search_default_mtrl_alpha.9.png
```

This is because that Android Studio build tool under Windows cannot handle file paths longer than 240 characters.

The build folder redirect code in the gradle file is to solve this problem. But unfortunately, this fix causes more build issues (like we just talked above).

**Comment by DIvu22** [comment]
same problem!..anyone knows how to solve this?

**Comment by DrMinaGhaly** [comment]
same problem here what is the solution ??

**Comment by Flekky69** [comment]
I bypassed the issue with workaround provided by @arshcaria:
```
Error:Failed to crunch file D:\Devel\GitHub\ud851-Exercises\Lesson05b-Smarter-GitHub-Repo-Search\T05b.02-Exercise-AddAsyncTaskLoader\app\build\intermediates\exploded-aar\com.android.support\appcompat-v7\25.1.1\res\drawable-hdpi-v4\abc_textfield_search_default_mtrl_alpha.9.png into D:\Devel\GitHub\ud851-Exercises\Lesson05b-Smarter-GitHub-Repo-Search\T05b.02-Exercise-AddAsyncTaskLoader\app\build\intermediates\res\merged\debug\drawable-hdpi-v4\abc_textfield_search_default_mtrl_alpha.9.png
Error:Execution failed for task ':app:mergeDebugResources'.
> Error: Failed to crunch file D:\Devel\GitHub\ud851-Exercises\Lesson05b-Smarter-GitHub-Repo-Search\T05b.02-Exercise-AddAsyncTaskLoader\app\build\intermediates\exploded-aar\com.android.support\appcompat-v7\25.1.1\res\drawable-hdpi-v4\abc_textfield_search_default_mtrl_alpha.9.png into D:\Devel\GitHub\ud851-Exercises\Lesson05b-Smarter-GitHub-Repo-Search\T05b.02-Exercise-AddAsyncTaskLoader\app\build\intermediates\res\merged\debug\drawable-hdpi-v4\abc_textfield_search_default_mtrl_alpha.9.png
```
simply:

1.  applying workaround provided by @arshcaria commenting redirect gradke code:
```allprojects {
    //String osName = System.getProperty("os.name").toLowerCase();
    //if (osName.contains("windows")) {
    //    buildDir = "C:/tmp/${rootProject.name}/${project.name}"
    //}
    repositories {
        jcenter()
    }
}
```

2. synchronizing the project (it fails), but it will be possible to proceed with step 3 

3. creating new activity (it is created)

4. reverting back changes in build.gradle file introduced with previous workaround and resync the project

It is something likely dirty, but it worked for me to advance with coding the project. 
Surely it would has been better moving the project directory to shorter path (as the error may occur when path to some file is too long), but I has been lazy.

**Comment by nonevietnam** [comment]
Thank everyone

**Comment by sudokoi** [comment]
The workaround as suggested by @Flekky69 is too lengthy. Creating an activity manually i.e.
     1. Create the java file and extend AppCompatActivity
     2. Create a layout resource file for the same
     3. Override onCreate
     4. Update AndroidManifest
is much simpler. I prefer doing these 4 steps instead.

**Comment by mrpeny** [comment]
I was doing like @MistNewt mentioned but the commenting out solution works for me too.

**Comment by DroidPulkit** [comment]
OMG, this bug is still here, nothing is working for me. Can anyone help me here?

**Comment by DroidPulkit** [comment]
Found the answer https://stackoverflow.com/a/42947592/4204668
Just delete the C;/tmp folder

**Comment by elwan7dev** [comment]
thanks a lot  for help

**Comment by GregIzzo** [comment]
@DroidPulkit you are right! Thanks for posting that link. I tried just deleting the subfolder in c:\tmp for my specific project, but that didn't work. You definitely need to delete the entire c:\tmp folder.

**Comment by paoramati** [comment]
The issue persists, was able to workaround using the @arshcaria method of commenting out within the Project's build.gradle file.

**Comment by swetac14** [comment]
Thank you @arshcaria  for the workaround.
This saved me a lot of time.

**Comment by blcktgr73** [comment]
Hi,
I just joined to this mailing list. Can you share what is the work around
details? I'm following the course and stuck in here.
SB

2018. 2. 12. 오전 10:34에 "swetac14" <notifications@github.com>님이 작성:

**Comment by swetac14** [comment]
@blcktgr73 
Checkout the following steps and you should be good.

1.  Comment out the following code in gradle file (build.gradle)

allprojects {
   // String osName = System.getProperty("os.name").toLowerCase();
   // if (osName.contains("windows")) {
   //     buildDir = "C:/tmp/${rootProject.name}/${project.name}"
   // }
    repositories {
        jcenter()
    }
}

2.  Use Sync Now at the top of the page to sync the project.
3. Add the new Empty Activity (Child Activity)
4. Uncomment the lines you commented out in the gradle file 
5. Sync the project again

**Comment by blcktgr73** [comment]
@swtac14
Thanks for quick update.
When I have test with Android Studio 3, only steps 1 and 2 are enough for
further testing.
This can make sense. I also have ubuntu setup and it works fine.
SB

2018-02-12 16:20 GMT+09:00 swetac14 <notifications@github.com>:

**Comment by aromanelli** [comment]
Deleting the C:\tmp folder worked for me.  I did not try the steps outlined by @arshcaria.

EDIT: On another lesson, even deleting the C:\tmp folder did not work.  I tried @arshcaria's instructions, and they worked.

So, both deleting the tmp folder, and commenting out the buildDir population worked, exclusively, in different projects/lessons.

**Comment by ManognaMutyala** [comment]
I think it's not about deleting C:\tmp, Just change the location from C:\tmp to the location where you have downloaded exercise repository, it worked fine for me!!

**Comment by akashengginer** [comment]
1) Comment out the following code in gradle file (build.gradle)

buildDir = "C:/tmp/${rootProject.name}/${project.name}"  ---comment this line

2) Use Sync Now at the top of the page to sync the project.
3) Add the new Empty Activity (Child Activity)
4) Uncomment the lines you commented out in the gradle file
5) Sync the project again

**Comment by elBachatero** [comment]
End of 2018 and the bug is still there. Android Studio is updated to the latest version. It "silently" fails to create the new activity. After the previously suggested commenting it's possible but then you have to revert back to get a proper build. Works but it ain't fancy.

**Comment by arshcaria** [comment]
> End of 2018 and the bug is still there. Android Studio is updated to the latest version. It "silently" fails to create the new activity. After the previously suggested commenting it's possible but then you have to revert back to get a proper build. Works but it ain't fancy.

You know what. Now I use only one partition (the C drive) on my Windows machine. This can save you from that build folder redirection problem. LOL

**Comment by PritishSehzpaul** [comment]
The error has something to do with the way gradle builds the app. I am a novice when it comes to gradle so I could not pinpoint the cause. But the solutions are:- 
Instead of commenting out 
```gradle 
if (osName.contains("windows")) { 
    buildDir = "C:/tmp/${rootProject.name}/${project.name}" 
} 
```
Do:-

1. Run a `gradle clean` in the exercise directory. You can do this via these ways:-
a) In Android Studio click on Gradle option on the right hand access bar(I guess, I don't know the exact term). Click on app/exercise name. It would be something like S04.01-Exercise-LaunchNewActivity(root). Select `Tasks>other`. Double click on `clean`.

b) **For command line** enthusiasts(feels cool), open command line and type
```cmd
gradlew clean
```
or for **powershell**, type
```shell
./gradlew clean
```
2. **Goto C: drive** in Windows, then **goto tmp folder**. Here find the folder having the exercise/app name having issues and delete it.

**Comment by aromanelli** [comment]
@PritishSehzpaul  See my comment above in this issue's comments.

@elBachatero The 'bug' is how the project is set up.  Its an old exercise/project, and the newer versions of Android Studio/Gradle have issues with it.  I haven't seen this bug outside of older Udacity projects.

**Comment by PritishSehzpaul** [comment]
@aromanelli You may have other folders in **tmp folder**. For eg. I used it to store temporary datasets while following a tensorflow tutorial.  That's why deleting the complete folder is not a good idea. Also, I have mentioned a new `gradle clean` approach that helps solve the issue and also points to the fact that issue was in fact due to gradle build. This is cleaner in my opinion and easier to understand.

**Comment by aromanelli** [comment]
@PritishSehzpaul Actually I referred my previous post because the deletion option for me did not always work (regardless if it had subdirs or not), so I don't think that you can say that just doing the clean/delete is the complete solution.  And for the record, I did do 'gradle clean' calls (I just didn't document that in my comments here).  I do definitely agree with you that its a good thing to try doing.

I'm guessing it may have something to do with the version of Gradle being used and the project hierarchy.  Maybe even the ${rootProject.name}/${project.name} values changing during the Gradle build cycle, since it seems to be a problem with the fact that it is an old project setup, as newer ones never have the problem.  @arshcaria solution makes me think that certain files have to be duplicated and be in two different locations, for the whole build process to work correctly, that one part of the process looks for certain files in location 1 and another part of the build process looks for the same files in location 2.  

If true, then that reinforces my thoughts that the project needs updating in its file system layout to support newer Gradle/AndroidStudio.  If Udacity would just redo that project with a newer version of Android Studio, then this problem would no longer occur.

In any case, good input all around.  :)

**Comment by PritishSehzpaul** [comment]
@aromanelli  Thanks for these insights! :')
