### ISSUE TITLE
No T02.02-Exercise-AddMenu

### ISSUE THREAD

**Issue by sidewalkjoe** [udacity/ud851-Exercises#7]
The exercise T02.02 where you learn to add a menu is not available.

**Comment by francisco-gamonal** [comment]
+1

**Comment by loren138** [comment]
Looks like it was deleted: https://github.com/udacity/ud851-Exercises/commit/b05be8f93f4484004f7e2443f5b63aa8297251b6   @JeremySilverTongue

**Comment by JeremySilverTongue** [comment]
Fixed in f10394f16cad062cb7ba857a784f158fafa1e175

Rebasing is hard :P
