### ISSUE TITLE
Project 2, PopulaMovies->Preferences->Download the Code

### ISSUE THREAD

**Issue by luqmanulkhair** [udacity/ud851-Exercises#72]
> QUIZ QUESTION
> Check the following choices that would make just the treble triangle and bass circle visible, in red.

The default value of  `private boolean showMid;` is false inside `VisualizerView` so one doesnot need to explicitly call `mVisualizerView.setShowMid(false);` This means only three choices are correct.

**Comment by johnshea** [comment]
Closing this issue as it is not related to the repo's code.
