### ISSUE TITLE
T04b.02-Exercise-OpenMap : Incorrect URI generated

### ISSUE THREAD

**Issue by aku97** [udacity/ud851-Exercises#75]
In current code, Uri builder has been used which puts a '/' after the 'geo:' part (as it has been passed as path). This leads to the app switching to the maps app, but not querying the address given, and instead opening up at default location, in a 'ready to search' state.
Maybe use something like
Uri mapUri = Uri.parse("geo:0,0?q="+Uri.encode(address));

**Comment by lednhatkhanh** [comment]
I have the same issue and using the `Uri.parse` works.
If I use the default code, I will get this uri: `geo:/0%2C0?Silver%20City%2C%20NM%2088061`

**Comment by sparky192** [comment]
I had the same issue. I found a workaround:
`Uri.Builder builder = new Uri.Builder();`
`builder.scheme("geo").encodedPath("0,0").appendQueryParameter("q",addressString);`

`Uri addressUri = builder.build();`

**Comment by johnshea** [comment]
Fixed.
