### ISSUE TITLE
T06.01 Incorrect TODO: The ID should not be in the strings.xml

### ISSUE THREAD

**Issue by gabor-meszaros** [udacity/ud851-Exercises#76]
Hi,

I really like the course, you are doing a great job!

I found an (let's say) error [in the TODO](https://github.com/udacity/ud851-Exercises/blob/student/Lesson06-Visualizer-Preferences/T06.01-Exercise-SetupTheActivity/app/src/main/java/android/example/com/visualizerpreferences/VisualizerActivity.java#L123):

    // action_settings, the id and title should be saved in strings.xml, the item should never

I think the ID should not be in the strings.xml. [You did not put it](https://github.com/udacity/ud851-Exercises/blob/student/Lesson06-Visualizer-Preferences/T06.01-Solution-SetupTheActivity/app/src/main/res/menu/visualizer_menu.xml) into [the strings.xml](https://github.com/udacity/ud851-Exercises/blob/student/Lesson06-Visualizer-Preferences/T06.01-Solution-SetupTheActivity/app/src/main/res/values/strings.xml) in the solution either.

Would you like me to create a PR if you confirm that this is really an error? Thanks!

**Comment by ceruleanotter** [comment]
Thanks @gabor-meszaros; I just updated the commit message!
