### ISSUE TITLE
T10.06 batteryManager.isCharging() API level 23 

### ISSUE THREAD

**Issue by fernando-almeida** [udacity/ud851-Exercises#77]
There seems to be a bug or misinterpretation of what isCharging should mean to the Android Core Development
https://developer.android.com/reference/android/os/BatteryManager.html#isCharging()

Even if the battery is full and the device is still connected to power I believe this method should still return true which is not the case in the emulator nor in the most recent Android OS version. These two conditions should not be treated as mutually exclusive as it seems to be the case.
My guess is that the main purpose of the BatteryManager service would be to adequately track changes related battery and keep a correct state for the user to query based on an effective model which it does not seem to be case for this matter.

**Comment by lid** [comment]
The behavior of `isCharging()` is a little wonky (as tested on API 25). It appears that even if the battery status is 2 (Charging) and the device is on AC, isCharging will not return true unless the battery level has actually incremented (e.g. via `adb shell dumpsys battery set level 50 && adb shell dumpsys battery set level 51`). At very least, this should be documented in the lesson notes. 

Also, if you fall back to the sticky broadcast intent, this relies instead on the battery charging status set e.g. via `adb shell dumpsys battery set status 2`.

In any case, the two methods for determining charging status in API >= 23 and API < 23 presented in the lesson are not equivalent. They are also different than checking whether the device is plugged in, i.e. they do not correspond to `ACTION_POWER_CONNECTED` and `ACTION_POWER_DISCONNECTED` as is implied in the lesson.

**Comment by DigitTeaser** [comment]
In the [BatteryManager](https://developer.android.com/reference/android/os/BatteryManager#isCharging()) document, the `isCharging()` method was described as below. 

> Return true if the battery is currently considered to be charging. This means that the device is plugged in and is supplying sufficient power that the battery level is going up (or the battery is fully charged). 

Therefore, what lid said was right. The `isCharging()` method only returns true when the battery level has actually incremented. I think the Android Framework team considered the situation that the device was plugged in some insufficient power. It usually happens when the device is charging using a power bank or through a car USB port.

**Comment by johnshea** [comment]
Closing this issue as it is not related to the repo's code.
