### ISSUE TITLE
T01.01-Exercices-CreateLayout

### ISSUE THREAD

**Issue by jim1399** [udacity/ud851-Exercises#78]
hello udacity;
i had a problem opening the project,, 
i ma using win 7 64bit,, with android studio 2.2.3 everything on my computer is working fine except for the exercise project that don't open properly,,,, i have attached a picture for the issue
thank you
![azaz](https://cloud.githubusercontent.com/assets/25832343/23046403/8544f122-f4a9-11e6-8390-ef1d38175c8e.png)

**Comment by taakasj** [comment]
How to resolve this issue?

**Comment by UngureanEugen** [comment]
Add constraint layout from Sdk Tools -> Support Repository.   
Check the response on stackoverflow https://stackoverflow.com/questions/37992187/gradle-sync-failed-could-not-find-constraint-layout1-0-0-alpha2
