### ISSUE TITLE
T02.06-Solution-AddPolish Bug

### ISSUE THREAD

**Issue by etman55** [udacity/ud851-Exercises#87]
i tried to make the GithubQueryTask AsyncTask to fetch the data every time it gets me error message.
when i tried to put "else" statment in the onPostExecute method like this
`
 @Override
        protected void onPostExecute(String githubSearchResults) {
            mLoadingIndicator.setVisibility(View.INVISIBLE);
            if (githubSearchResults != null && !githubSearchResults.equals("")) {
                showJsonDataView();
                mSearchResultsTextView.setText(githubSearchResults);
            }else
            showErrorMessage();
        }
`
the code worked correctly and it fetched the requested data

**Comment by Halfacht** [comment]
Isn't that the same as they show here:
https://classroom.udacity.com/courses/ud851/lessons/e5d74e43-743c-455e-9a70-7545a2da9783/concepts/591ff476-467a-4696-8501-3b6fa465118c
Starting at frame: 1:58

**Comment by etman55** [comment]
i think yeah it's the same in this video but in the code here i think they forgot to add "else" in it when i opened this issue but i think they fixed it now :)
