### ISSUE TITLE
T10.04 -> Scheduled notification on Solution not working on SIM.

### ISSUE THREAD

**Issue by rsd-raul** [udacity/ud851-Exercises#99]
I'm getting a very erratic bahaviour when testing both my code and the solution on the simulator (Nexus 5X - Android 7.0), I've double checked it's "charging" but for some reason it doesn't apear to be working.

On the other hand, if tested on a physical device (Note 3 - Android 4.4) it works perfectly.

Is this somehow expected or is it a known issue?

**Comment by rsd-raul** [comment]
Similar issue in T10.06, in this case the explanation has been given in the Issue #77, maybe a similar problem happens in T10.04 with the simulator?

In any case, probably a small warning or explanation for future students will solve the issue.

**Comment by HakHanKoh** [comment]
How rigid are your constraints set?
http://stackoverflow.com/questions/41443891/firebase-job-dispatcher-doesnt-trigger-the-service-class

**Comment by johnshea** [comment]
Closing as I am unable to duplicate.
